import type { Category, Supplier, VehicleModel, Part, PurchaseOrder, PurchaseOrderItem, SalesOrder, SalesOrderItem, StockMovement, ProductHistoryLog, Customer, Return, DamagedStock, StockAdjustment, AppNotification, Helmet } from './schema';

export const INITIAL_HELMETS: Helmet[] = [
  {
    id: 'hlm-101',
    productName: 'SMK Stellar Gloss Black',
    brand: 'SMK',
    model: 'Stellar',
    sku: 'SMK-001',
    barcode: '890123400001',
    purchasePrice: 4200,
    wholesalePrice: 5000,
    salePrice: 5800,
    stockLevel: 18,
    reorderPoint: 5,
    maxStock: 50,
    weight: '1450g',
    size: 'L',
    colour: 'Gloss Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Aerodynamic energy-impact thermoplastic shell helmet with Pinlock-ready visor, breath deflector, and removable hypoallergenic liner.',
    imageUrl: '',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-102',
    productName: 'LS2 FF353 Rapid Solid Matte Black',
    brand: 'LS2',
    model: 'Rapid FF353',
    sku: 'LS2-101',
    barcode: '890123400002',
    purchasePrice: 5100,
    wholesalePrice: 6100,
    salePrice: 7200,
    stockLevel: 4,
    reorderPoint: 8,
    maxStock: 40,
    weight: '1300g',
    size: 'M',
    colour: 'Matte Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Ultra-light HPTT composite shell with quick release visor system, dynamic flow-through ventilation, and breath guard.',
    imageUrl: '',
    createdAt: '2026-07-03T11:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-103',
    productName: 'Axor Apex Venom Neon Yellow',
    brand: 'Axor',
    model: 'Apex Venom',
    sku: 'AX-201',
    barcode: '890123400003',
    purchasePrice: 4800,
    wholesalePrice: 5600,
    salePrice: 6500,
    stockLevel: 24,
    reorderPoint: 8,
    maxStock: 60,
    weight: '1500g',
    size: 'XL',
    colour: 'Neon Yellow / Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'ECE 22.05 & DOT certified aggressive graphic helmet featuring integrated dual-visor system and chin curtain.',
    imageUrl: '',
    createdAt: '2026-07-05T09:30:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-104',
    productName: 'Steelbird SBA-7 7SEVEN Flip-Up',
    brand: 'Steelbird',
    model: 'SBA-7 7SEVEN',
    sku: 'SB-301',
    barcode: '890123400004',
    purchasePrice: 2600,
    wholesalePrice: 3100,
    salePrice: 3799,
    stockLevel: 0,
    reorderPoint: 6,
    maxStock: 35,
    weight: '1400g',
    size: 'L',
    colour: 'Titanium Grey',
    category: 'Modular',
    gearType: 'Helmets',
    description: 'Versatile modular flip-up helmet with high-impact engineering ABS casing, micro-metric buckle, and anti-scratch visor.',
    imageUrl: '',
    createdAt: '2026-07-08T14:15:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-105',
    productName: 'MT Helmets Thunder 4 SV Solid',
    brand: 'MT',
    model: 'Thunder 4 SV',
    sku: 'MT-401',
    barcode: '890123400005',
    purchasePrice: 7500,
    wholesalePrice: 8800,
    salePrice: 9900,
    stockLevel: 12,
    reorderPoint: 4,
    maxStock: 25,
    weight: '1550g',
    size: 'M',
    colour: 'Pearl White',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'ECE 22.06 certified next-generation touring helmet with internal drop-down sun visor and emergency release cheek pads.',
    imageUrl: '',
    createdAt: '2026-07-10T16:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-106',
    productName: 'Studds Thunder D1 Open Face',
    brand: 'Studds',
    model: 'Thunder D1',
    sku: 'ST-501',
    barcode: '890123400006',
    purchasePrice: 1400,
    wholesalePrice: 1750,
    salePrice: 2150,
    stockLevel: 35,
    reorderPoint: 10,
    maxStock: 80,
    weight: '980g',
    size: 'M',
    colour: 'Matt Blue',
    category: 'Open Face',
    gearType: 'Helmets',
    description: 'Lightweight urban commuter helmet with high-density EPS liner, wide peripheral vision, and quick-release strap.',
    imageUrl: '',
    createdAt: '2026-07-12T12:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-107',
    productName: 'AGV K1 S Speed Red',
    brand: 'AGV',
    model: 'K1 S',
    sku: 'AGV-601',
    barcode: '890123400007',
    purchasePrice: 18500,
    wholesalePrice: 21000,
    salePrice: 24500,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 15,
    weight: '1500g',
    size: 'L',
    colour: 'Speed Red / Black',
    category: 'Dual Sport',
    gearType: 'Helmets',
    description: 'MotoGP-derived aero spoiler, high-resistance thermoplastic shell, and 190° horizontal field of vision.',
    imageUrl: '',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-108',
    productName: 'Arai Tour-X4 Adventure Matte White',
    brand: 'Arai',
    model: 'Tour-X4',
    sku: 'AR-701',
    barcode: '890123400008',
    purchasePrice: 42000,
    wholesalePrice: 48000,
    salePrice: 55000,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 10,
    weight: '1620g',
    size: 'XL',
    colour: 'Matte White',
    category: 'Adventure',
    gearType: 'Helmets',
    description: 'Flagship adventure helmet built with Super Complex Laminate Construction (SCLC) for unmatched impact protection.',
    imageUrl: '',
    createdAt: '2026-07-20T14:30:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-109',
    productName: 'HJC RPHA 11 Carbon Solid',
    brand: 'HJC',
    model: 'RPHA 11',
    sku: 'HJC-801',
    barcode: '890123400009',
    purchasePrice: 28000,
    wholesalePrice: 32000,
    salePrice: 36500,
    stockLevel: 8,
    reorderPoint: 3,
    maxStock: 20,
    weight: '1250g',
    size: 'L',
    colour: 'Carbon Weave',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Full Carbon Fiber Outer Shell racing helmet with RapidFire II visor replacement system and max airflow ventilation.',
    imageUrl: '',
    createdAt: '2026-07-22T08:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  }
];


export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Brake System', description: 'Disc pads, calipers, rotors, brake lines, and master cylinders.' },
  { id: 'cat-2', name: 'Engine Parts', description: 'Pistons, rings, valves, gaskets, filters, and spark plugs.' },
  { id: 'cat-3', name: 'Electrical', description: 'Stators, CDI units, wiring harnesses, starter motors, and batteries.' },
  { id: 'cat-4', name: 'Transmission', description: 'Chains, sprockets, clutches, gearbox gears, and belts.' },
  { id: 'cat-5', name: 'Suspension', description: 'Fork seals, shock absorbers, swingarms, and linkages.' },
  { id: 'cat-6', name: 'Filters', description: 'Air filters, oil filters, fuel filters.' },
  { id: 'cat-7', name: 'Wheels', description: 'Tires, rims, spokes, bearings, and axles.' },
  { id: 'cat-8', name: 'Body Parts', description: 'Fairings, mudguards, mirrors, frames.' },
  { id: 'cat-9', name: 'Accessories', description: 'Luggage racks, phone mounts, crash guards.' },
  { id: 'cat-10', name: 'Lubricants', description: 'Engine oil, chain lube, brake fluid, coolant.' },
  { id: 'cat-11', name: 'Others', description: 'General nuts, bolts, and miscellaneous washers.' },
  { id: 'cat-12', name: 'Control Cables', description: 'Accelerator, clutch, brake, and speedometer cables.' }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup-1', name: 'Nippon Performance Parts', email: 'orders@nipponparts.jp', phone: '+81-3-5555-0192', contactPerson: 'Takeshi Sato', leadTimeDays: 7 },
  { id: 'sup-2', name: 'Brembo Racing Supply', email: 'wholesale@bremboracing.it', phone: '+39-035-123456', contactPerson: 'Luca Rossi', leadTimeDays: 14 },
  { id: 'sup-3', name: 'Apex Drive Logistics', email: 'sales@apexdrive.com', phone: '+1-800-555-0143', contactPerson: 'Sarah Jenkins', leadTimeDays: 5 },
  { id: 'sup-4', name: 'MotoShield Electricals', email: 'support@motoshield.tw', phone: '+886-2-2777-1234', contactPerson: 'David Chen', leadTimeDays: 10 }
];

export const INITIAL_VEHICLES: VehicleModel[] = [
  { id: 'veh-1', make: 'Yamaha', model: 'YZF-R1', year: '2020-2024', engineCC: '998cc' },
  { id: 'veh-2', make: 'Honda', model: 'CB500X', year: '2019-2023', engineCC: '471cc' },
  { id: 'veh-3', make: 'Kawasaki', model: 'Ninja 400', year: '2018-2024', engineCC: '399cc' },
  { id: 'veh-4', make: 'Suzuki', model: 'V-Strom 650', year: '2017-2023', engineCC: '645cc' },
  { id: 'veh-5', make: 'KTM', model: 'Duke 390', year: '2020-2024', engineCC: '373cc' },
  { id: 'veh-6', make: 'Bajaj', model: 'Pulsar 150', year: '2015-2024', engineCC: '149.5cc' },
  { id: 'veh-7', make: 'Bajaj', model: 'Pulsar 180', year: '2015-2023', engineCC: '178.6cc' },
  { id: 'veh-8', make: 'Bajaj', model: 'Pulsar 220', year: '2016-2024', engineCC: '220cc' },
  { id: 'veh-9', make: 'Bajaj', model: 'Discover 150', year: '2014-2020', engineCC: '144.8cc' },
  { id: 'veh-10', make: 'TVS', model: 'Apache 200', year: '2018-2024', engineCC: '197.7cc' },
  { id: 'veh-11', make: 'Yamaha', model: 'FZSv3', year: '2019-2024', engineCC: '149cc' },
  { id: 'veh-12', make: 'Yamaha', model: 'FZS V4', year: '2023-2025', engineCC: '149cc' },
  { id: 'veh-13', make: 'Yamaha', model: 'Rayz', year: '2018-2024', engineCC: '125cc' },
  { id: 'veh-14', make: 'Honda', model: 'Dio', year: '2017-2024', engineCC: '109.5cc' },
  { id: 'veh-15', make: 'KTM', model: 'Duke 200', year: '2018-2024', engineCC: '199.5cc' },
  { id: 'veh-16', make: 'KTM', model: 'Duke 250', year: '2019-2024', engineCC: '248.8cc' },
  { id: 'veh-17', make: 'Royal Enfield', model: 'Bullet 350', year: '2016-2024', engineCC: '349cc' },
  { id: 'veh-18', make: 'Hero', model: 'Super Splendor', year: '2015-2024', engineCC: '125cc' },
  { id: 'veh-19', make: 'Bajaj', model: 'Pulsar NS200', year: '2012-2024', engineCC: '199.5cc' },
  { id: 'veh-20', make: 'Bajaj', model: 'Discover 125', year: '2011-2020', engineCC: '124.5cc' },
  { id: 'veh-21', make: 'Bajaj', model: 'Discover 100', year: '2009-2015', engineCC: '94.3cc' },
  { id: 'veh-22', make: 'Honda', model: 'CB Hornet / Trigger', year: '2015-2022', engineCC: '162.7cc' },
  { id: 'veh-23', make: 'TVS', model: 'Apache RTR 160 4V', year: '2018-2024', engineCC: '159.7cc' },
  { id: 'veh-24', make: 'Honda', model: 'CB Shine', year: '2015-2024', engineCC: '124cc' },
  { id: 'veh-25', make: 'TVS', model: 'NTorq 125', year: '2018-2024', engineCC: '124.8cc' },
  { id: 'veh-26', make: 'Yamaha', model: 'Fascino 125 FI', year: '2020-2024', engineCC: '125cc' },
  { id: 'veh-27', make: 'Hero', model: 'Glamour', year: '2014-2024', engineCC: '124.7cc' },
  { id: 'veh-28', make: 'Honda', model: 'Unicorn 150/160', year: '2010-2024', engineCC: '162.7cc' },
  { id: 'veh-29', make: 'Yamaha', model: 'Saluto 125', year: '2015-2022', engineCC: '125cc' }
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'cab-acc-1',
    sku: 'CAB-ACC-HRO-SPL',
    name: 'ACC Cable Super Splendor / Glamour',
    oemNumber: 'OEM-HRO-ACC-SPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 29,
    reorderPoint: 5,
    maxStock: 50,
    unit: 'Pcs',
    binLocation: 'CAB-01',
    description: 'Accelerator cable for Hero Super Splendor and Hero Glamour.',
    brand: 'Hero',
    barcode: '890100100001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18', 'veh-27']
  },
  {
    id: 'cab-acc-2',
    sku: 'CAB-ACC-BAJ-NS200-CARB',
    name: 'ACC Cable Pulsar NS 200 Carburetor',
    oemNumber: 'OEM-BAJ-ACC-NS200C',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-02',
    description: 'Accelerator cable for Bajaj Pulsar 200 NS / NS 200 (Carburetor version).',
    brand: 'Bajaj',
    barcode: '890100100002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-3',
    sku: 'CAB-ACC-BAJ-NS200-FI',
    name: 'ACC Cable NS 200cc FI',
    oemNumber: 'OEM-BAJ-ACC-NS200FI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-03',
    description: 'Accelerator cable for Bajaj Pulsar NS 200 (Fuel Injection version).',
    brand: 'Bajaj',
    barcode: '890100100003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-4',
    sku: 'CAB-ACC-BAJ-P220',
    name: 'ACC Cable 220 Pulsar',
    oemNumber: 'OEM-BAJ-ACC-P220',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 19,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-04',
    description: 'Accelerator cable for Bajaj Pulsar 220 / 220F.',
    brand: 'Bajaj',
    barcode: '890100100004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'cab-acc-5',
    sku: 'CAB-ACC-BAJ-DIS125-NEW',
    name: 'ACC Cable Discover 125cc New',
    oemNumber: 'OEM-BAJ-ACC-D125N',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-05',
    description: 'Accelerator cable for Bajaj Discover 125 (New model).',
    brand: 'Bajaj',
    barcode: '890100100005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-6',
    sku: 'CAB-ACC-BAJ-P150',
    name: 'ACC Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-ACC-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-06',
    description: 'Accelerator cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-7',
    sku: 'CAB-ACC-HON-HOR-TRIG',
    name: 'ACC Cable Hornet/Trigger',
    oemNumber: 'OEM-HON-ACC-HT160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-07',
    description: 'Accelerator cable for Honda CB Hornet 160R / CB Trigger.',
    brand: 'Honda',
    barcode: '890100100007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-22']
  },
  {
    id: 'cab-acc-8',
    sku: 'CAB-ACC-TVS-RTR160-4V',
    name: 'ACC Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-ACC-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-08',
    description: 'Accelerator cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-acc-9',
    sku: 'CAB-ACC-BAJ-DIS100-125M',
    name: 'ACC Cable Discover 100cc/Discover 125M',
    oemNumber: 'OEM-BAJ-ACC-D100M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-09',
    description: 'Accelerator cable for Bajaj Discover 100cc / Discover 125M.',
    brand: 'Bajaj',
    barcode: '890100100009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20', 'veh-21']
  },
  {
    id: 'cab-clu-1',
    sku: 'CAB-CLU-TVS-RTR160-4V',
    name: 'Clutch Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-CLU-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-10',
    description: 'Clutch control cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-clu-2',
    sku: 'CAB-CLU-BAJ-P150',
    name: 'Clutch Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-CLU-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-11',
    description: 'Clutch control cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-10',
    sku: 'CAB-ACC-BAJ-DIS125-OLD',
    name: 'ACC Cable Discover 125cc Old',
    oemNumber: 'OEM-BAJ-ACC-D125O',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-12',
    description: 'Accelerator cable for Bajaj Discover 125 (Old model).',
    brand: 'Bajaj',
    barcode: '890100100012',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-11',
    sku: 'CAB-ACC-BAJ-DIS125-ST',
    name: 'ACC Cable Discover 125 ST',
    oemNumber: 'OEM-BAJ-ACC-D125ST',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-13',
    description: 'Accelerator cable for Bajaj Discover 125 ST.',
    brand: 'Bajaj',
    barcode: '890100100013',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-12',
    sku: 'CAB-ACC-BAJ-DIS125-M',
    name: 'ACC Cable Discover 125 M',
    oemNumber: 'OEM-BAJ-ACC-D125M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-14',
    description: 'Accelerator cable for Bajaj Discover 125 M.',
    brand: 'Bajaj',
    barcode: '890100100014',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-13',
    sku: 'CAB-ACC-HON-SHINE',
    name: 'ACC Cable Honda Shine',
    oemNumber: 'OEM-HON-ACC-SHINE',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 15,
    reorderPoint: 4,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-15',
    description: 'Accelerator cable for Honda CB Shine 125.',
    brand: 'Honda',
    barcode: '890100100015',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'cab-acc-14',
    sku: 'CAB-ACC-YAM-FZV3-FI',
    name: 'ACC Cable Yamaha FZ V3 / FZ-FI / FZS-FI',
    oemNumber: 'OEM-YAM-ACC-FZV3',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-16',
    description: 'Accelerator cable for Yamaha FZ V3, FZ-FI, and FZS-FI.',
    brand: 'Yamaha',
    barcode: '890100100016',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11', 'veh-12']
  },
  {
    id: 'cab-acc-15',
    sku: 'CAB-ACC-TVS-NTORQ-BS6',
    name: 'ACC Cable TVS NTORQ BS6 FI',
    oemNumber: 'OEM-TVS-ACC-NTORQ6',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-17',
    description: 'Accelerator cable for TVS NTORQ 125 BS-6 FI.',
    brand: 'TVS',
    barcode: '890100100017',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-25']
  },
  {
    id: 'cab-acc-16',
    sku: 'CAB-ACC-YAM-FASC-RAYZR',
    name: 'ACC Cable Yamaha Fascino 125 FI / Ray-ZR 125',
    oemNumber: 'OEM-YAM-ACC-F125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-18',
    description: 'Accelerator cable for Yamaha Fascino 125 FI and Ray-ZR 125 FI.',
    brand: 'Yamaha',
    barcode: '890100100018',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13', 'veh-26']
  },
  {
    id: 'cab-acc-17',
    sku: 'CAB-ACC-HRO-GLM-FI',
    name: 'ACC Cable Hero Glamour FI',
    oemNumber: 'OEM-HRO-ACC-GLMFI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-19',
    description: 'Accelerator cable for Hero Glamour FI (Fuel Injection model).',
    brand: 'Hero',
    barcode: '890100100019',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-27']
  },
  {
    id: 'cab-acc-18',
    sku: 'CAB-ACC-HON-UNICORN',
    name: 'ACC Cable Honda Unicorn',
    oemNumber: 'OEM-HON-ACC-UNI160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-20',
    description: 'Accelerator cable for Honda Unicorn 150 / 160.',
    brand: 'Honda',
    barcode: '890100100020',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cab-acc-19',
    sku: 'CAB-ACC-YAM-SALUTO',
    name: 'ACC Cable Yamaha Saluto',
    oemNumber: 'OEM-YAM-ACC-SAL125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-21',
    description: 'Accelerator cable for Yamaha Saluto 125.',
    brand: 'Yamaha',
    barcode: '890100100021',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-29']
  }
];

// ─── Sales Orders & Items ─────────────────────────────────────────────────────
export const INITIAL_SALES_ORDERS: SalesOrder[] = [];
export const INITIAL_SALES_ORDER_ITEMS: SalesOrderItem[] = [];


export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [];
export const INITIAL_PURCHASE_ORDER_ITEMS: PurchaseOrderItem[] = [];

// ─── Phase 2: Seeding logs ───────────────────────────────────────────────────
export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [];
export const INITIAL_HISTORY_LOGS: ProductHistoryLog[] = [];

// ─── Phase 4: Customers ───────────────────────────────────────────────────────
export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'cust-1', name: 'DownTown Moto Workshop', email: 'orders@dtmoto.com', phone: '+60-3-2145-6789', address: '12 Jalan Bukit Bintang, Kuala Lumpur', type: 'TRADE', notes: 'Primary trade customer. Net-30 credit terms.', createdAt: '2026-01-15T09:00:00Z' },
  { id: 'cust-2', name: 'SpeedKings Racing', email: 'parts@speedkings.my', phone: '+60-4-7123-4567', address: '88 Jalan Raja Laut, Penang', type: 'WHOLESALE', notes: 'Bulk orders for racing season. Priority customer.', createdAt: '2026-02-01T10:30:00Z' },
  { id: 'cust-3', name: 'Ahmad Faruqi', email: 'ahmad.faruqi@gmail.com', phone: '+60-12-345-6789', address: '45 Taman Melati, Ampang', type: 'RETAIL', notes: 'Regular retail buyer. Honda CB500X enthusiast.', createdAt: '2026-03-10T14:00:00Z' },
  { id: 'cust-4', name: 'MotoFix Garage Klang', email: 'motofix.klang@gmail.com', phone: '+60-3-3371-9900', address: '7 Jalan Meru, Klang', type: 'TRADE', notes: 'Workshop specializing in Kawasaki & Suzuki.', createdAt: '2026-04-05T11:00:00Z' },
  { id: 'cust-5', name: 'Hafiz Motorsports', email: 'hafiz@hafizmotors.com', phone: '+60-11-2233-4455', address: '23 Jalan Cheras, Kuala Lumpur', type: 'WHOLESALE', notes: 'Preferred wholesale discount 15%.', createdAt: '2026-05-20T09:00:00Z' },
  { id: 'cust-6', name: 'Lee Ming Parts Sdn Bhd', email: 'lee.ming@leeparts.com.my', phone: '+60-3-7887-1122', address: '55 Jalan SS2, Petaling Jaya', type: 'TRADE', notes: 'Premium trade partner.', createdAt: '2026-06-01T08:00:00Z' }
];

// ─── Phase 4: Returns ────────────────────────────────────────────────────────
export const INITIAL_RETURNS: Return[] = [];

// ─── Phase 4: Damaged Stock & Adjustments ─────────────────────────────────────
export const INITIAL_DAMAGED_STOCK: DamagedStock[] = [];
export const INITIAL_STOCK_ADJUSTMENTS: StockAdjustment[] = [];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [];

