import type { Category, Supplier, VehicleModel, Part, PurchaseOrder, PurchaseOrderItem, SalesOrder, SalesOrderItem, StockMovement, ProductHistoryLog, Customer, Return, DamagedStock, StockAdjustment, AppNotification, Helmet } from './schema';

export const INITIAL_HELMETS: Helmet[] = [];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-12', name: 'Control Cables', description: 'Accelerator, clutch, brake, and speedometer cables.' },
  { id: 'cat-13', name: 'Chain Lube & Spray', description: 'Chain lubricants, maintenance sprays, and color spray paints.' },
  { id: 'cat-14', name: 'Brakes', description: 'Brake rods, shoes, pads, and braking system components.' },
  { id: 'cat-15', name: 'Chain Sprocket', description: 'Chain sprockets, sprocket kits, and engine cam chains.' }
];

export const INITIAL_SUPPLIERS: Supplier[] = [];

export const INITIAL_VEHICLES: VehicleModel[] = [
  { id: 'veh-1', make: 'Yamaha', model: 'YZF-R1', year: '2020-2024', engineCC: '998cc' },
  { id: 'veh-2', make: 'Honda', model: 'CB500X', year: '2019-2023', engineCC: '471cc' },
  { id: 'veh-3', make: 'Kawasaki', model: 'Ninja 400', year: '2018-2024', engineCC: '399cc' },
  { id: 'veh-4', make: 'Suzuki', model: 'V-Strom 650', year: '2017-2023', engineCC: '645cc' },
  { id: 'veh-5', make: 'KTM', model: 'Duke 390', year: '2020-2024', engineCC: '373cc' },
  { id: 'veh-6', make: 'Bajaj', model: 'Pulsar 150', year: '2015-2024', engineCC: '149.5cc' },
  { id: 'veh-7', make: 'Bajaj', model: 'Pulsar 180', year: '2015-2023', engineCC: '178.6cc' },
  { id: 'veh-8', make: 'Bajaj', model: 'Pulsar 220', year: '2016-2024', engineCC: '220cc' },
  { id: 'veh-9', make: 'Bajaj', model: 'Discover 150', year: '2014-2020', engineCC: '144.8cc' },
  { id: 'veh-10', make: 'TVS', model: 'Apache 200', year: '2018-2024', engineCC: '197.7cc' },
  { id: 'veh-11', make: 'Yamaha', model: 'FZSv3', year: '2019-2024', engineCC: '149cc' },
  { id: 'veh-12', make: 'Yamaha', model: 'FZS V4', year: '2023-2025', engineCC: '149cc' },
  { id: 'veh-13', make: 'Yamaha', model: 'Rayz', year: '2018-2024', engineCC: '125cc' },
  { id: 'veh-14', make: 'Honda', model: 'Dio', year: '2017-2024', engineCC: '109.5cc' },
  { id: 'veh-15', make: 'KTM', model: 'Duke 200', year: '2018-2024', engineCC: '199.5cc' },
  { id: 'veh-16', make: 'KTM', model: 'Duke 250', year: '2019-2024', engineCC: '248.8cc' },
  { id: 'veh-17', make: 'Royal Enfield', model: 'Bullet 350', year: '2016-2024', engineCC: '349cc' },
  { id: 'veh-18', make: 'Hero', model: 'Super Splendor', year: '2015-2024', engineCC: '125cc' },
  { id: 'veh-19', make: 'Bajaj', model: 'Pulsar NS200', year: '2012-2024', engineCC: '199.5cc' },
  { id: 'veh-20', make: 'Bajaj', model: 'Discover 125', year: '2011-2020', engineCC: '124.5cc' },
  { id: 'veh-21', make: 'Bajaj', model: 'Discover 100', year: '2009-2015', engineCC: '94.3cc' },
  { id: 'veh-22', make: 'Honda', model: 'CB Hornet / Trigger', year: '2015-2022', engineCC: '162.7cc' },
  { id: 'veh-23', make: 'TVS', model: 'Apache RTR 160 4V', year: '2018-2024', engineCC: '159.7cc' },
  { id: 'veh-24', make: 'Honda', model: 'CB Shine', year: '2015-2024', engineCC: '124cc' },
  { id: 'veh-25', make: 'TVS', model: 'NTorq 125', year: '2018-2024', engineCC: '124.8cc' },
  { id: 'veh-26', make: 'Yamaha', model: 'Fascino 125 FI', year: '2020-2024', engineCC: '125cc' },
  { id: 'veh-27', make: 'Hero', model: 'Glamour', year: '2014-2024', engineCC: '124.7cc' },
  { id: 'veh-28', make: 'Honda', model: 'Unicorn 150/160', year: '2010-2024', engineCC: '162.7cc' },
  { id: 'veh-29', make: 'Yamaha', model: 'Saluto 125', year: '2015-2022', engineCC: '125cc' },
  { id: 'veh-30', make: 'Honda', model: 'Dio BS6 FI', year: '2020-2024', engineCC: '109.5cc' },
  { id: 'veh-31', make: 'Yamaha', model: 'YZF-R15 V2', year: '2011-2018', engineCC: '149.8cc' },
  { id: 'veh-32', make: 'Honda', model: 'Grazia 125', year: '2017-2024', engineCC: '124cc' },
  { id: 'veh-33', make: 'Yamaha', model: 'FZ 16', year: '2008-2015', engineCC: '153cc' },
  { id: 'veh-34', make: 'Yamaha', model: 'SZ-R 153', year: '2010-2016', engineCC: '153cc' },
  { id: 'veh-35', make: 'Bajaj', model: 'Avenger 150/180/220', year: '2015-2024', engineCC: '220cc' },
  { id: 'veh-36', make: 'Yamaha', model: 'YZF-R15', year: '2018-2024', engineCC: '155cc' },
  { id: 'veh-37', make: 'Bajaj', model: 'Platina 100/110', year: '2015-2024', engineCC: '115cc' },
  { id: 'veh-38', make: 'Hero', model: 'CBZ Xtreme', year: '2008-2015', engineCC: '149.2cc' },
  { id: 'veh-39', make: 'Yamaha', model: 'Gladiator 125', year: '2006-2011', engineCC: '123.7cc' },
  { id: 'veh-40', make: 'TVS', model: 'Raider 125', year: '2021-2024', engineCC: '124.8cc' },
  { id: 'veh-41', make: 'Bajaj', model: 'Pulsar N160', year: '2022-2024', engineCC: '164.8cc' },
  { id: 'veh-42', make: 'Bajaj', model: 'Pulsar NS160', year: '2017-2024', engineCC: '160.3cc' },
  { id: 'veh-43', make: 'Yamaha', model: 'FZ 25 / 250', year: '2017-2023', engineCC: '249cc' }
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'cab-acc-1',
    sku: 'CAB-ACC-HRO-SPL',
    name: 'ACC Cable Super Splendor / Glamour',
    oemNumber: 'OEM-HRO-ACC-SPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 29,
    reorderPoint: 5,
    maxStock: 50,
    unit: 'Pcs',
    binLocation: 'CAB-01',
    description: 'Accelerator cable for Hero Super Splendor and Hero Glamour.',
    brand: 'Hero',
    barcode: '890100100001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18', 'veh-27']
  },
  {
    id: 'cab-acc-2',
    sku: 'CAB-ACC-BAJ-NS200-CARB',
    name: 'ACC Cable Pulsar NS 200 Carburetor',
    oemNumber: 'OEM-BAJ-ACC-NS200C',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-02',
    description: 'Accelerator cable for Bajaj Pulsar 200 NS / NS 200 (Carburetor version).',
    brand: 'Bajaj',
    barcode: '890100100002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-3',
    sku: 'CAB-ACC-BAJ-NS200-FI',
    name: 'ACC Cable NS 200cc FI',
    oemNumber: 'OEM-BAJ-ACC-NS200FI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-03',
    description: 'Accelerator cable for Bajaj Pulsar NS 200 (Fuel Injection version).',
    brand: 'Bajaj',
    barcode: '890100100003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-4',
    sku: 'CAB-ACC-BAJ-P220',
    name: 'ACC Cable 220 Pulsar',
    oemNumber: 'OEM-BAJ-ACC-P220',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 19,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-04',
    description: 'Accelerator cable for Bajaj Pulsar 220 / 220F.',
    brand: 'Bajaj',
    barcode: '890100100004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'cab-acc-5',
    sku: 'CAB-ACC-BAJ-DIS125-NEW',
    name: 'ACC Cable Discover 125cc New',
    oemNumber: 'OEM-BAJ-ACC-D125N',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-05',
    description: 'Accelerator cable for Bajaj Discover 125 (New model).',
    brand: 'Bajaj',
    barcode: '890100100005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-6',
    sku: 'CAB-ACC-BAJ-P150',
    name: 'ACC Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-ACC-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-06',
    description: 'Accelerator cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-7',
    sku: 'CAB-ACC-HON-HOR-TRIG',
    name: 'ACC Cable Hornet/Trigger',
    oemNumber: 'OEM-HON-ACC-HT160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-07',
    description: 'Accelerator cable for Honda CB Hornet 160R / CB Trigger.',
    brand: 'Honda',
    barcode: '890100100007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-22']
  },
  {
    id: 'cab-acc-8',
    sku: 'CAB-ACC-TVS-RTR160-4V',
    name: 'ACC Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-ACC-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-08',
    description: 'Accelerator cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-acc-9',
    sku: 'CAB-ACC-BAJ-DIS100-125M',
    name: 'ACC Cable Discover 100cc/Discover 125M',
    oemNumber: 'OEM-BAJ-ACC-D100M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-09',
    description: 'Accelerator cable for Bajaj Discover 100cc / Discover 125M.',
    brand: 'Bajaj',
    barcode: '890100100009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20', 'veh-21']
  },
  {
    id: 'cab-clu-1',
    sku: 'CAB-CLU-TVS-RTR160-4V',
    name: 'Clutch Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-CLU-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 19,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-10',
    description: 'Clutch control cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-clu-2',
    sku: 'CAB-CLU-BAJ-P150',
    name: 'Clutch Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-CLU-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 16,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-11',
    description: 'Clutch control cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-10',
    sku: 'CAB-ACC-BAJ-DIS125-OLD',
    name: 'ACC Cable Discover 125cc Old',
    oemNumber: 'OEM-BAJ-ACC-D125O',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-12',
    description: 'Accelerator cable for Bajaj Discover 125 (Old model).',
    brand: 'Bajaj',
    barcode: '890100100012',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-11',
    sku: 'CAB-ACC-BAJ-DIS125-ST',
    name: 'ACC Cable Discover 125 ST',
    oemNumber: 'OEM-BAJ-ACC-D125ST',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-13',
    description: 'Accelerator cable for Bajaj Discover 125 ST.',
    brand: 'Bajaj',
    barcode: '890100100013',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-12',
    sku: 'CAB-ACC-BAJ-DIS125-M',
    name: 'ACC Cable Discover 125 M',
    oemNumber: 'OEM-BAJ-ACC-D125M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-14',
    description: 'Accelerator cable for Bajaj Discover 125 M.',
    brand: 'Bajaj',
    barcode: '890100100014',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-13',
    sku: 'CAB-ACC-HON-SHINE',
    name: 'ACC Cable Honda Shine',
    oemNumber: 'OEM-HON-ACC-SHINE',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 15,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-15',
    description: 'Accelerator cable for Honda CB Shine 125.',
    brand: 'Honda',
    barcode: '890100100015',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'cab-acc-14',
    sku: 'CAB-ACC-YAM-FZV3-FI',
    name: 'ACC Cable Yamaha FZ V3 / FZ-FI / FZS-FI',
    oemNumber: 'OEM-YAM-ACC-FZV3',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-16',
    description: 'Accelerator cable for Yamaha FZ V3, FZ-FI, and FZS-FI.',
    brand: 'Yamaha',
    barcode: '890100100016',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11', 'veh-12']
  },
  {
    id: 'cab-acc-15',
    sku: 'CAB-ACC-TVS-NTORQ-BS6',
    name: 'ACC Cable TVS NTORQ BS6 FI',
    oemNumber: 'OEM-TVS-ACC-NTORQ6',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-17',
    description: 'Accelerator cable for TVS NTORQ 125 BS-6 FI.',
    brand: 'TVS',
    barcode: '890100100017',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-25']
  },
  {
    id: 'cab-acc-16',
    sku: 'CAB-ACC-YAM-FASC-RAYZR',
    name: 'ACC Cable Yamaha Fascino 125 FI / Ray-ZR 125',
    oemNumber: 'OEM-YAM-ACC-F125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-18',
    description: 'Accelerator cable for Yamaha Fascino 125 FI and Ray-ZR 125 FI.',
    brand: 'Yamaha',
    barcode: '890100100018',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13', 'veh-26']
  },
  {
    id: 'cab-acc-17',
    sku: 'CAB-ACC-HRO-GLM-FI',
    name: 'ACC Cable Hero Glamour FI',
    oemNumber: 'OEM-HRO-ACC-GLMFI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-19',
    description: 'Accelerator cable for Hero Glamour FI (Fuel Injection model).',
    brand: 'Hero',
    barcode: '890100100019',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-27']
  },
  {
    id: 'cab-acc-18',
    sku: 'CAB-ACC-HON-UNICORN',
    name: 'ACC Cable Honda Unicorn',
    oemNumber: 'OEM-HON-ACC-UNI160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-20',
    description: 'Accelerator cable for Honda Unicorn 150 / 160.',
    brand: 'Honda',
    barcode: '890100100020',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cab-acc-19',
    sku: 'CAB-ACC-YAM-SALUTO',
    name: 'ACC Cable Yamaha Saluto',
    oemNumber: 'OEM-YAM-ACC-SAL125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-21',
    description: 'Accelerator cable for Yamaha Saluto 125.',
    brand: 'Yamaha',
    barcode: '890100100021',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-29']
  },
  {
    id: 'spr-1',
    sku: 'SPR-BLK-01',
    name: 'SPRAY - Black',
    oemNumber: 'OEM-SPR-BLK',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-01',
    description: 'Aerosol spray paint - Black finish.',
    brand: 'Universal',
    barcode: '890200100001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-2',
    sku: 'SPR-YEL-01',
    name: 'SPRAY - Yellow',
    oemNumber: 'OEM-SPR-YEL',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-02',
    description: 'Aerosol spray paint - Yellow finish.',
    brand: 'Universal',
    barcode: '890200100002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-3',
    sku: 'SPR-RED-LT',
    name: 'SPRAY - Red (Light)',
    oemNumber: 'OEM-SPR-RED-LT',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-03',
    description: 'Aerosol spray paint - Light Red finish.',
    brand: 'Universal',
    barcode: '890200100003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-4',
    sku: 'SPR-RED-DK',
    name: 'SPRAY - Red (Dark)',
    oemNumber: 'OEM-SPR-RED-DK',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-04',
    description: 'Aerosol spray paint - Dark Red finish.',
    brand: 'Universal',
    barcode: '890200100004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-5',
    sku: 'SPR-SLV-01',
    name: 'SPRAY - Silver',
    oemNumber: 'OEM-SPR-SLV',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-05',
    description: 'Aerosol spray paint - Silver finish.',
    brand: 'Universal',
    barcode: '890200100005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-6',
    sku: 'SPR-GRN-01',
    name: 'SPRAY - Green',
    oemNumber: 'OEM-SPR-GRN',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 7,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-06',
    description: 'Aerosol spray paint - Green finish.',
    brand: 'Universal',
    barcode: '890200100006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-7',
    sku: 'SPR-WHT-01',
    name: 'SPRAY - White',
    oemNumber: 'OEM-SPR-WHT',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 0,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-07',
    description: 'Aerosol spray paint - White finish.',
    brand: 'Universal',
    barcode: '890200100007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'spr-8',
    sku: 'SPR-BLU-01',
    name: 'SPRAY - Blue',
    oemNumber: 'OEM-SPR-BLU',
    categoryId: 'cat-13',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Can',
    binLocation: 'SPR-08',
    description: 'Aerosol spray paint - Blue finish.',
    brand: 'Universal',
    barcode: '890200100008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: []
  },
  {
    id: 'cab-acc-20',
    sku: 'CAB-ACC-HON-DIO-NM',
    name: 'ACC Cable Dio / NM',
    oemNumber: 'OEM-HON-ACC-DIONM',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-22',
    description: 'Accelerator cable for Honda Dio / NM.',
    brand: 'Honda',
    barcode: '890100100022',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14']
  },
  {
    id: 'cab-acc-21',
    sku: 'CAB-ACC-HON-DIO-BS6',
    name: 'ACC Cable Dio BS6 FI',
    oemNumber: 'OEM-HON-ACC-DIOBS6',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-23',
    description: 'Accelerator cable for Honda Dio BS6 FI.',
    brand: 'Honda',
    barcode: '890100100023',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-30']
  },
  {
    id: 'cab-acc-22',
    sku: 'CAB-ACC-RE-BULLET',
    name: 'ACC Cable Bullet 350',
    oemNumber: 'OEM-RE-ACC-BUL350',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 7,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-24',
    description: 'Accelerator cable for Royal Enfield Bullet 350.',
    brand: 'Royal Enfield',
    barcode: '890100100024',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-17']
  },
  {
    id: 'cab-acc-23',
    sku: 'CAB-ACC-YAM-R15V2',
    name: 'ACC Cable Yamaha R15 V2',
    oemNumber: 'OEM-YAM-ACC-R15V2',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-25',
    description: 'Accelerator cable for Yamaha YZF-R15 V2.',
    brand: 'Yamaha',
    barcode: '890100100025',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-31']
  },
  {
    id: 'cab-brk-1',
    sku: 'CAB-BRK-FR-L-DIO',
    name: 'Front Brake Cable (L) Dio',
    oemNumber: 'OEM-HON-BRK-DIOL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-01',
    description: 'Front left brake cable for Honda Dio.',
    brand: 'Honda',
    barcode: '890100200001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14']
  },
  {
    id: 'cab-brk-2',
    sku: 'CAB-BRK-FR-R-DIO',
    name: 'Front Brake Cable (R) Dio',
    oemNumber: 'OEM-HON-BRK-DIOR',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-02',
    description: 'Front right brake cable for Honda Dio.',
    brand: 'Honda',
    barcode: '890100200002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14']
  },
  {
    id: 'cab-brk-3',
    sku: 'CAB-BRK-FR-BAJ-DIS-NEW',
    name: 'Front Brake Cable Discover New',
    oemNumber: 'OEM-BAJ-BRK-D125N',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-03',
    description: 'Front brake cable for Bajaj Discover New.',
    brand: 'Bajaj',
    barcode: '890100200003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-brk-4',
    sku: 'CAB-BRK-FR-BAJ-DIS-OLD',
    name: 'Front Brake Cable Discover Old',
    oemNumber: 'OEM-BAJ-BRK-D125O',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-04',
    description: 'Front brake cable for Bajaj Discover Old.',
    brand: 'Bajaj',
    barcode: '890100200004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-brk-5',
    sku: 'CAB-BRK-FR-YAM-RAYZ',
    name: 'Front Brake Cable Yamaha Ray Z',
    oemNumber: 'OEM-YAM-BRK-RAYZ',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-05',
    description: 'Front brake cable for Yamaha Ray Z.',
    brand: 'Yamaha',
    barcode: '890100200005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13']
  },
  {
    id: 'cab-brk-6',
    sku: 'CAB-BRK-FR-HRO-SPL',
    name: 'Front Brake Cable Super Splendor',
    oemNumber: 'OEM-HRO-BRK-SSPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-06',
    description: 'Front brake cable for Hero Super Splendor.',
    brand: 'Hero',
    barcode: '890100200006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18']
  },
  {
    id: 'cab-brk-7',
    sku: 'CAB-BRK-FR-LR-DIO',
    name: 'Front Brake Cable (L+R) Dio',
    oemNumber: 'OEM-HON-BRK-DIOLR',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-07',
    description: 'Front brake cable combo (Left + Right) for Honda Dio.',
    brand: 'Honda',
    barcode: '890100200007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14']
  },
  {
    id: 'cab-brk-8',
    sku: 'CAB-BRK-RR-HON-GRZ-DIO',
    name: 'Rear Brake Cable Grazia / Dio N/M',
    oemNumber: 'OEM-HON-BRK-GRZDIO',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 16,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-BRK-08',
    description: 'Rear brake cable for Honda Grazia and Honda Dio N/M.',
    brand: 'Honda',
    barcode: '890100200008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14', 'veh-32']
  },
  {
    id: 'cab-clu-3',
    sku: 'CAB-CLU-HON-UNI-160',
    name: 'Clutch Cable Unicorn 160',
    oemNumber: 'OEM-HON-CLU-U160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-03',
    description: 'Clutch control cable for Honda Unicorn 160.',
    brand: 'Honda',
    barcode: '890100300003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cab-clu-4',
    sku: 'CAB-CLU-HRO-SPL',
    name: 'Clutch Cable Super Splendor',
    oemNumber: 'OEM-HRO-CLU-SSPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-04',
    description: 'Clutch control cable for Hero Super Splendor.',
    brand: 'Hero',
    barcode: '890100300004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18']
  },
  {
    id: 'cab-clu-5',
    sku: 'CAB-CLU-BAJ-DIS-125ST',
    name: 'Clutch Cable Discover 125 ST',
    oemNumber: 'OEM-BAJ-CLU-D125ST',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-05',
    description: 'Clutch control cable for Bajaj Discover 125 ST.',
    brand: 'Bajaj',
    barcode: '890100300005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-clu-6',
    sku: 'CAB-CLU-BAJ-P220',
    name: 'Clutch Cable Pulsar 220',
    oemNumber: 'OEM-BAJ-CLU-P220',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-06',
    description: 'Clutch control cable for Bajaj Pulsar 220.',
    brand: 'Bajaj',
    barcode: '890100300006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'cab-clu-7',
    sku: 'CAB-CLU-YAM-FZ16',
    name: 'Clutch Cable Yamaha FZ 16',
    oemNumber: 'OEM-YAM-CLU-FZ16',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-07',
    description: 'Clutch control cable for Yamaha FZ 16.',
    brand: 'Yamaha',
    barcode: '890100300007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-33']
  },
  {
    id: 'cab-clu-8',
    sku: 'CAB-CLU-YAM-SZR',
    name: 'Clutch Cable Yamaha SZ-R',
    oemNumber: 'OEM-YAM-CLU-SZR',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-08',
    description: 'Clutch control cable for Yamaha SZ-R 153.',
    brand: 'Yamaha',
    barcode: '890100300008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-34']
  },
  {
    id: 'cab-clu-9',
    sku: 'CAB-CLU-BAJ-NS200',
    name: 'Clutch Cable Pulsar NS 200',
    oemNumber: 'OEM-BAJ-CLU-NS200',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-09',
    description: 'Clutch control cable for Bajaj Pulsar NS 200.',
    brand: 'Bajaj',
    barcode: '890100300009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-clu-10',
    sku: 'CAB-CLU-HON-UNICORN',
    name: 'Clutch Cable Honda Unicorn',
    oemNumber: 'OEM-HON-CLU-UNI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 19,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-10',
    description: 'Clutch control cable for Honda Unicorn.',
    brand: 'Honda',
    barcode: '890100300010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cab-clu-11',
    sku: 'CAB-CLU-TVS-RTR200-4V',
    name: 'Clutch Cable RTR 200 4V',
    oemNumber: 'OEM-TVS-CLU-RTR2004V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 12,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-11',
    description: 'Clutch control cable for TVS Apache RTR 200 4V.',
    brand: 'TVS',
    barcode: '890100300011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-10']
  },
  {
    id: 'cab-clu-12',
    sku: 'CAB-CLU-BAJ-DIS-125BS4',
    name: 'Clutch Cable Discover 125 BS4',
    oemNumber: 'OEM-BAJ-CLU-D125BS4',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-12',
    description: 'Clutch control cable for Bajaj Discover 125 BS4.',
    brand: 'Bajaj',
    barcode: '890100300012',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-clu-13',
    sku: 'CAB-CLU-HON-HORNET',
    name: 'Clutch Cable Hornet',
    oemNumber: 'OEM-HON-CLU-HRNT',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-13',
    description: 'Clutch control cable for Honda CB Hornet 160R.',
    brand: 'Honda',
    barcode: '890100300013',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-22']
  },
  {
    id: 'cab-clu-14',
    sku: 'CAB-CLU-BAJ-AVENGER',
    name: 'Clutch Cable Bajaj Avenger',
    oemNumber: 'OEM-BAJ-CLU-AVG',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 7,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-14',
    description: 'Clutch control cable for Bajaj Avenger 150/180/220.',
    brand: 'Bajaj',
    barcode: '890100300014',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-35']
  },
  {
    id: 'cab-clu-15',
    sku: 'CAB-CLU-YAM-SALUTO',
    name: 'Clutch Cable Yamaha Saluto',
    oemNumber: 'OEM-YAM-CLU-SAL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-15',
    description: 'Clutch control cable for Yamaha Saluto 125.',
    brand: 'Yamaha',
    barcode: '890100300015',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-29']
  },
  {
    id: 'cab-clu-16',
    sku: 'CAB-CLU-RE-BULLET',
    name: 'Clutch Cable Bullet 350',
    oemNumber: 'OEM-RE-CLU-BUL350',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-16',
    description: 'Clutch control cable for Royal Enfield Bullet 350.',
    brand: 'Royal Enfield',
    barcode: '890100300016',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-17']
  },
  {
    id: 'cab-clu-17',
    sku: 'CAB-CLU-YAM-R15',
    name: 'Clutch Cable Yamaha R15',
    oemNumber: 'OEM-YAM-CLU-R15',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-CLU-17',
    description: 'Clutch control cable for Yamaha YZF-R15.',
    brand: 'Yamaha',
    barcode: '890100300017',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-36']
  },
  // ─── Speedometer Cables (cat-12) ──────────────────────────────────────────
  {
    id: 'cab-spd-1',
    sku: 'CAB-SPD-YAM-SZR',
    name: 'Speedometer Cable Yamaha SZ-R',
    oemNumber: 'OEM-YAM-SPD-SZR',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 12,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-01',
    description: 'Speedometer control cable for Yamaha SZ-R / SZ-RR.',
    brand: 'Yamaha',
    barcode: '890100400001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-34']
  },
  {
    id: 'cab-spd-2',
    sku: 'CAB-SPD-HRO-SPL',
    name: 'Speedometer Cable Super Splendor',
    oemNumber: 'OEM-HRO-SPD-SPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-02',
    description: 'Speedometer control cable for Hero Super Splendor.',
    brand: 'Hero',
    barcode: '890100400002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18']
  },
  {
    id: 'cab-spd-3',
    sku: 'CAB-SPD-YAM-RAYZ',
    name: 'Speedometer Cable Yamaha Ray Z',
    oemNumber: 'OEM-YAM-SPD-RAYZ',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-03',
    description: 'Speedometer control cable for Yamaha Ray Z.',
    brand: 'Yamaha',
    barcode: '890100400003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13']
  },
  {
    id: 'cab-spd-4',
    sku: 'CAB-SPD-HON-DIO',
    name: 'Speedometer Cable Dio N/M',
    oemNumber: 'OEM-HON-SPD-DIO',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 12,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-04',
    description: 'Speedometer control cable for Honda Dio New Model.',
    brand: 'Honda',
    barcode: '890100400004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14', 'veh-30']
  },
  {
    id: 'cab-spd-5',
    sku: 'CAB-SPD-HON-SHN',
    name: 'Speedometer Cable Honda Shine',
    oemNumber: 'OEM-HON-SPD-SHN',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-05',
    description: 'Speedometer control cable for Honda CB Shine.',
    brand: 'Honda',
    barcode: '890100400005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'cab-spd-6',
    sku: 'CAB-SPD-BAJ-PLT',
    name: 'Speedometer Cable Platina',
    oemNumber: 'OEM-BAJ-SPD-PLT',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-06',
    description: 'Speedometer control cable for Bajaj Platina.',
    brand: 'Bajaj',
    barcode: '890100400006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-37']
  },
  {
    id: 'cab-spd-7',
    sku: 'CAB-SPD-BAJ-DISC125',
    name: 'Speedometer Cable Discover 125 BS4',
    oemNumber: 'OEM-BAJ-SPD-DISC125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 5,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-07',
    description: 'Speedometer control cable for Bajaj Discover 125 BS4.',
    brand: 'Bajaj',
    barcode: '890100400007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-spd-8',
    sku: 'CAB-SPD-YAM-FAS',
    name: 'Speedometer Cable Fascino',
    oemNumber: 'OEM-YAM-SPD-FAS',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-08',
    description: 'Speedometer control cable for Yamaha Fascino 125.',
    brand: 'Yamaha',
    barcode: '890100400008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-26']
  },
  {
    id: 'cab-spd-9',
    sku: 'CAB-SPD-YAM-RAYZ-NM',
    name: 'Speedometer Cable Ray Z N/M',
    oemNumber: 'OEM-YAM-SPD-RAYZNM',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-09',
    description: 'Speedometer control cable for Yamaha Ray Z New Model.',
    brand: 'Yamaha',
    barcode: '890100400009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13']
  },
  {
    id: 'cab-spd-10',
    sku: 'CAB-SPD-YAM-RAYZ-FAS',
    name: 'Speedometer Cable Ray Z / Fascino',
    oemNumber: 'OEM-YAM-SPD-RAYZFAS',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 5,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-SPD-10',
    description: 'Speedometer control cable common for Yamaha Ray Z and Fascino.',
    brand: 'Yamaha',
    barcode: '890100400010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13', 'veh-26']
  },
  // ─── Brakes (cat-14) ────────────────────────────────────────────────────────
  {
    id: 'brk-rod-1',
    sku: 'BRK-ROD-BAJ-PUL180',
    name: 'Brake Rod Pulsar UG3 / UG4 / 180cc',
    oemNumber: 'OEM-BAJ-BRK-PUL180',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 16,
    reorderPoint: 5,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-01',
    description: 'Rear brake rod for Bajaj Pulsar UG3 / UG4 / 180cc.',
    brand: 'Bajaj',
    barcode: '890100500001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6', 'veh-7']
  },
  {
    id: 'brk-rod-2',
    sku: 'BRK-ROD-HON-UNI',
    name: 'Brake Rod Honda Unicorn',
    oemNumber: 'OEM-HON-BRK-UNI',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 3,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-02',
    description: 'Rear brake rod for Honda Unicorn 150/160.',
    brand: 'Honda',
    barcode: '890100500002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'brk-rod-3',
    sku: 'BRK-ROD-HRO-CBZ',
    name: 'Brake Rod CBZ Xtreme',
    oemNumber: 'OEM-HRO-BRK-CBZ',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-03',
    description: 'Rear brake rod for Hero Honda CBZ Xtreme.',
    brand: 'Hero',
    barcode: '890100500003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-38']
  },
  {
    id: 'brk-rod-4',
    sku: 'BRK-ROD-BAJ-PUL200D',
    name: 'Brake Rod Pulsar 200 Digital',
    oemNumber: 'OEM-BAJ-BRK-PUL200D',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-04',
    description: 'Rear brake rod for Bajaj Pulsar 200 Digital.',
    brand: 'Bajaj',
    barcode: '890100500004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'brk-rod-5',
    sku: 'BRK-ROD-YAM-FZ',
    name: 'Brake Rod Yamaha FZ',
    oemNumber: 'OEM-YAM-BRK-FZ',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-05',
    description: 'Rear brake rod for Yamaha FZ16 / FZS.',
    brand: 'Yamaha',
    barcode: '890100500005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11', 'veh-33']
  },
  {
    id: 'brk-rod-6',
    sku: 'BRK-ROD-HRO-SPL-GLM',
    name: 'Brake Rod Super Splendor / Glamour',
    oemNumber: 'OEM-HRO-BRK-SPLGLM',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 3,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-06',
    description: 'Rear brake rod for Hero Super Splendor and Glamour.',
    brand: 'Hero',
    barcode: '890100500006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18', 'veh-27']
  },
  {
    id: 'brk-rod-7',
    sku: 'BRK-ROD-TVS-RTR',
    name: 'Brake Rod TVS Apache RTR',
    oemNumber: 'OEM-TVS-BRK-RTR',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 3,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-07',
    description: 'Rear brake rod for TVS Apache RTR 160/180.',
    brand: 'TVS',
    barcode: '890100500007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'brk-rod-8',
    sku: 'BRK-ROD-BAJ-DISC-ALL',
    name: 'Brake Rod Discover ALL',
    oemNumber: 'OEM-BAJ-BRK-DISCALL',
    categoryId: 'cat-14',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 7,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'BRK-ROD-08',
    description: 'Rear brake rod for Bajaj Discover all models.',
    brand: 'Bajaj',
    barcode: '890100500008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-9', 'veh-20', 'veh-21']
  },
  // ─── Chain Sprockets (cat-15) ──────────────────────────────────────────────
  {
    id: 'spk-1',
    sku: 'SPK-TVS-RTR200-4V',
    name: 'Chain Sprocket RTR 200cc 4V',
    oemNumber: 'OEM-TVS-SPK-RTR200',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-01',
    description: 'Chain sprocket kit for TVS Apache RTR 200 4V.',
    brand: 'TVS',
    barcode: '890100600001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-10']
  },
  {
    id: 'spk-2',
    sku: 'SPK-BAJ-DISC-185',
    name: 'Chain Sprocket 185 Discover',
    oemNumber: 'OEM-BAJ-SPK-DISC185',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 3,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-02',
    description: 'Chain sprocket kit #185 for Bajaj Discover.',
    brand: 'Bajaj',
    barcode: '890100600002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'spk-3',
    sku: 'SPK-BAJ-PUL220-139',
    name: 'Chain Sprocket 139 Pulsar 220',
    oemNumber: 'OEM-BAJ-SPK-PUL220',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Set',
    binLocation: 'SPK-03',
    description: 'Chain sprocket kit #139 for Bajaj Pulsar 220.',
    brand: 'Bajaj',
    barcode: '890100600003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'spk-4',
    sku: 'SPK-TVS-RTR-135',
    name: 'Chain Sprocket 135 RTR 2valve old',
    oemNumber: 'OEM-TVS-SPK-RTR135',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-04',
    description: 'Chain sprocket kit #135 for TVS RTR 2-valve old model.',
    brand: 'TVS',
    barcode: '890100600004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'spk-5',
    sku: 'SPK-HON-SHN-172',
    name: 'Chain Sprocket 172 Shine HEAVY',
    oemNumber: 'OEM-HON-SPK-SHN172',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 3,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-05',
    description: 'Heavy chain sprocket kit #172 for Honda CB Shine.',
    brand: 'Honda',
    barcode: '890100600005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'spk-6',
    sku: 'SPK-HON-HOR160-229',
    name: 'Chain Sprocket 229 Hornet 160cc',
    oemNumber: 'OEM-HON-SPK-HOR229',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-06',
    description: 'Chain sprocket kit #229 for Honda CB Hornet 160R.',
    brand: 'Honda',
    barcode: '890100600006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-22']
  },
  {
    id: 'spk-7',
    sku: 'SPK-BAJ-DISC-149',
    name: 'Chain Sprocket 149 Discover',
    oemNumber: 'OEM-BAJ-SPK-DISC149',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-07',
    description: 'Chain sprocket kit #149 for Bajaj Discover.',
    brand: 'Bajaj',
    barcode: '890100600007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'spk-8',
    sku: 'SPK-BAJ-NS160-214',
    name: 'Chain Sprocket 214 160,150 NS/AS pulsar',
    oemNumber: 'OEM-BAJ-SPK-NS214',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-08',
    description: 'Chain sprocket kit #214 for Bajaj Pulsar 150/160 NS/AS.',
    brand: 'Bajaj',
    barcode: '890100600008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-42']
  },
  {
    id: 'spk-9',
    sku: 'SPK-BAJ-N160-405',
    name: 'Chain Sprocket 405 N160cc',
    oemNumber: 'OEM-BAJ-SPK-N160',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-09',
    description: 'Chain sprocket kit #405 for Bajaj Pulsar N160.',
    brand: 'Bajaj',
    barcode: '890100600009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-41']
  },
  {
    id: 'spk-10',
    sku: 'SPK-YAM-FZV3-316',
    name: 'Chain Sprocket 316 FZV3',
    oemNumber: 'OEM-YAM-SPK-FZV3-316',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Set',
    binLocation: 'SPK-10',
    description: 'Chain sprocket kit #316 for Yamaha FZ V3 / FZS-FI.',
    brand: 'Yamaha',
    barcode: '890100600010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11']
  },
  {
    id: 'spk-11',
    sku: 'SPK-BAJ-AVG150-220',
    name: 'Chain Sprocket 220 Avenger 150cc',
    oemNumber: 'OEM-BAJ-SPK-AVG220',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-11',
    description: 'Chain sprocket kit #220 for Bajaj Avenger 150cc.',
    brand: 'Bajaj',
    barcode: '890100600011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-35']
  },
  {
    id: 'spk-12',
    sku: 'SPK-TVS-RTR160-4V',
    name: 'Chain Sprocket RTR 160 4v',
    oemNumber: 'OEM-TVS-SPK-RTR160-4V',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-12',
    description: 'Chain sprocket kit for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100600012',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'spk-13',
    sku: 'SPK-YAM-SZRR-165',
    name: 'Chain Sprocket SZRR 165',
    oemNumber: 'OEM-YAM-SPK-SZRR165',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-13',
    description: 'Chain sprocket kit #165 for Yamaha SZ-RR.',
    brand: 'Yamaha',
    barcode: '890100600013',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-34']
  },
  {
    id: 'spk-14',
    sku: 'SPK-BAJ-PUL180-160',
    name: 'Chain Sprocket 160 Pulsar 180cc',
    oemNumber: 'OEM-BAJ-SPK-PUL180-160',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Set',
    binLocation: 'SPK-14',
    description: 'Chain sprocket kit #160 for Bajaj Pulsar 180cc.',
    brand: 'Bajaj',
    barcode: '890100600014',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-7']
  },
  {
    id: 'spk-15',
    sku: 'SPK-HRO-SPL-79',
    name: 'Chain Sprocket 79 Super Splendor',
    oemNumber: 'OEM-HRO-SPK-SPL79',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-15',
    description: 'Chain sprocket kit #79 for Hero Super Splendor.',
    brand: 'Hero',
    barcode: '890100600015',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18']
  },
  {
    id: 'spk-16',
    sku: 'SPK-BAJ-PUL-DD-294',
    name: 'Chain Sprocket 294 Pulsar double disc',
    oemNumber: 'OEM-BAJ-SPK-PULDD294',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-16',
    description: 'Chain sprocket kit #294 for Bajaj Pulsar Double Disc.',
    brand: 'Bajaj',
    barcode: '890100600016',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6', 'veh-7']
  },
  {
    id: 'spk-17',
    sku: 'SPK-BAJ-NS200-183',
    name: 'Chain Sprocket 183 NS200cc',
    oemNumber: 'OEM-BAJ-SPK-NS183',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-17',
    description: 'Chain sprocket kit #183 for Bajaj Pulsar NS200.',
    brand: 'Bajaj',
    barcode: '890100600017',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'spk-18',
    sku: 'SPK-YAM-FZV2-143',
    name: 'Chain Sprocket 143 FZV2',
    oemNumber: 'OEM-YAM-SPK-FZV2-143',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-18',
    description: 'Chain sprocket kit #143 for Yamaha FZ V2.',
    brand: 'Yamaha',
    barcode: '890100600018',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11', 'veh-33']
  },
  {
    id: 'spk-19',
    sku: 'SPK-BAJ-PUL150-105',
    name: 'Chain Sprocket 105 pulsar 150',
    oemNumber: 'OEM-BAJ-SPK-PUL105',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 13,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Set',
    binLocation: 'SPK-19',
    description: 'Chain sprocket kit #105 for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100600019',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'spk-20',
    sku: 'SPK-YAM-GLAD-145',
    name: 'Chain Sprocket 145 Galaditor SS',
    oemNumber: 'OEM-YAM-SPK-GLAD145',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-20',
    description: 'Chain sprocket kit #145 for Yamaha Gladiator SS.',
    brand: 'Yamaha',
    barcode: '890100600020',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-39']
  },
  {
    id: 'spk-21',
    sku: 'SPK-YAM-GLAD-99',
    name: 'Chain Sprocket 99 Galaditor SS',
    oemNumber: 'OEM-YAM-SPK-GLAD99',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-21',
    description: 'Chain sprocket kit #99 for Yamaha Gladiator SS.',
    brand: 'Yamaha',
    barcode: '890100600021',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-39']
  },
  {
    id: 'spk-22',
    sku: 'SPK-TVS-RTR-148',
    name: 'Chain Sprocket 148 RTR',
    oemNumber: 'OEM-TVS-SPK-RTR148',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-22',
    description: 'Chain sprocket kit #148 for TVS Apache RTR.',
    brand: 'TVS',
    barcode: '890100600022',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'spk-23',
    sku: 'SPK-BAJ-DISC-170',
    name: 'Chain Sprocket 170 Discover',
    oemNumber: 'OEM-BAJ-SPK-DISC170',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-23',
    description: 'Chain sprocket kit #170 for Bajaj Discover.',
    brand: 'Bajaj',
    barcode: '890100600023',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'spk-24',
    sku: 'SPK-BAJ-DISC125-144',
    name: 'Chain Sprocket 144 Discover 125cc',
    oemNumber: 'OEM-BAJ-SPK-DISC144',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-24',
    description: 'Chain sprocket kit #144 for Bajaj Discover 125cc.',
    brand: 'Bajaj',
    barcode: '890100600024',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'spk-25',
    sku: 'SPK-TVS-RAID125-407',
    name: 'Chain Spocket 407 Raider 125cc',
    oemNumber: 'OEM-TVS-SPK-RAID407',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-25',
    description: 'Chain sprocket kit #407 for TVS Raider 125.',
    brand: 'TVS',
    barcode: '890100600025',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-40']
  },
  {
    id: 'spk-26',
    sku: 'SPK-RE-BULLET',
    name: 'Chain Sprocket Bullet',
    oemNumber: 'OEM-RE-SPK-BULLET',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 0,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Set',
    binLocation: 'SPK-26',
    description: 'Chain sprocket kit for Royal Enfield Bullet 350.',
    brand: 'Royal Enfield',
    barcode: '890100600026',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-17']
  },
  // ─── Cam Chains (cat-15) ───────────────────────────────────────────────────
  {
    id: 'cam-1',
    sku: 'CAM-BAJ-PUL150',
    name: 'Cam Chain Pulsar 150cc',
    oemNumber: 'OEM-BAJ-CAM-PUL150',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAM-01',
    description: 'Engine timing / cam chain for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100700001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cam-2',
    sku: 'CAM-BAJ-PUL200',
    name: 'Cam chain 200cc pulsar',
    oemNumber: 'OEM-BAJ-CAM-PUL200',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 13,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAM-02',
    description: 'Engine timing / cam chain for Bajaj Pulsar 200cc / 220cc.',
    brand: 'Bajaj',
    barcode: '890100700002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'cam-3',
    sku: 'CAM-HON-SHINE',
    name: 'Cam chain Shine Honda',
    oemNumber: 'OEM-HON-CAM-SHN',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 8,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAM-03',
    description: 'Engine timing / cam chain for Honda CB Shine.',
    brand: 'Honda',
    barcode: '890100700003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'cam-4',
    sku: 'CAM-HON-UNI160',
    name: 'Cam chain Unicorn 160cc',
    oemNumber: 'OEM-HON-CAM-UNI160',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAM-04',
    description: 'Engine timing / cam chain for Honda Unicorn 160cc.',
    brand: 'Honda',
    barcode: '890100700004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cam-5',
    sku: 'CAM-BAJ-NS160',
    name: 'Cam chain Ns160cc Pulsar',
    oemNumber: 'OEM-BAJ-CAM-NS160',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-05',
    description: 'Engine timing / cam chain for Bajaj Pulsar NS160.',
    brand: 'Bajaj',
    barcode: '890100700005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-42']
  },
  {
    id: 'cam-6',
    sku: 'CAM-YAM-FZ250',
    name: 'Cam chain Fz250cc',
    oemNumber: 'OEM-YAM-CAM-FZ250',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-06',
    description: 'Engine timing / cam chain for Yamaha FZ 250cc.',
    brand: 'Yamaha',
    barcode: '890100700006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-43']
  },
  {
    id: 'cam-7',
    sku: 'CAM-TVS-RTR200',
    name: 'Cam chain RTR 200cc',
    oemNumber: 'OEM-TVS-CAM-RTR200',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-07',
    description: 'Engine timing / cam chain for TVS Apache RTR 200 4V.',
    brand: 'TVS',
    barcode: '890100700007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-10']
  },
  {
    id: 'cam-8',
    sku: 'CAM-TVS-RTR160-4V',
    name: 'Cam chain RTR 4v 160cc',
    oemNumber: 'OEM-TVS-CAM-RTR160-4V',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 0,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-08',
    description: 'Engine timing / cam chain for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100700008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cam-9',
    sku: 'CAM-YAM-GLAD',
    name: 'Cam chain Gladiator',
    oemNumber: 'OEM-YAM-CAM-GLAD',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-09',
    description: 'Engine timing / cam chain for Yamaha Gladiator.',
    brand: 'Yamaha',
    barcode: '890100700009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-39']
  },
  {
    id: 'cam-10',
    sku: 'CAM-HON-DIO-OLD',
    name: 'Cam chain Dio old',
    oemNumber: 'OEM-HON-CAM-DIO-OLD',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-10',
    description: 'Engine timing / cam chain for Honda Dio old model.',
    brand: 'Honda',
    barcode: '890100700010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-14']
  },
  {
    id: 'cam-11',
    sku: 'CAM-HRO-SPL',
    name: 'Cam chain Super splendor',
    oemNumber: 'OEM-HRO-CAM-SPL',
    categoryId: 'cat-15',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 1,
    reorderPoint: 2,
    maxStock: 15,
    unit: 'Pcs',
    binLocation: 'CAM-11',
    description: 'Engine timing / cam chain for Hero Super Splendor.',
    brand: 'Hero',
    barcode: '890100700011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18']
  }
];

// ─── Sales Orders & Items ─────────────────────────────────────────────────────
export const INITIAL_SALES_ORDERS: SalesOrder[] = [];
export const INITIAL_SALES_ORDER_ITEMS: SalesOrderItem[] = [];


export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [];
export const INITIAL_PURCHASE_ORDER_ITEMS: PurchaseOrderItem[] = [];

// ─── Phase 2: Seeding logs ───────────────────────────────────────────────────
export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [];
export const INITIAL_HISTORY_LOGS: ProductHistoryLog[] = [];

export const INITIAL_CUSTOMERS: Customer[] = [];

// ─── Phase 4: Returns ────────────────────────────────────────────────────────
export const INITIAL_RETURNS: Return[] = [];

// ─── Phase 4: Damaged Stock & Adjustments ─────────────────────────────────────
export const INITIAL_DAMAGED_STOCK: DamagedStock[] = [];
export const INITIAL_STOCK_ADJUSTMENTS: StockAdjustment[] = [];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [];

