import type { Category, Supplier, VehicleModel, Part, PurchaseOrder, PurchaseOrderItem, SalesOrder, SalesOrderItem, StockMovement, ProductHistoryLog, Customer, Return, DamagedStock, StockAdjustment, AppNotification, Helmet } from './schema';

export const INITIAL_HELMETS: Helmet[] = [
  {
    id: 'hlm-101',
    productName: 'SMK Stellar Gloss Black',
    brand: 'SMK',
    model: 'Stellar',
    sku: 'SMK-001',
    barcode: '890123400001',
    purchasePrice: 4200,
    wholesalePrice: 5000,
    salePrice: 5800,
    stockLevel: 18,
    reorderPoint: 5,
    maxStock: 50,
    weight: '1450g',
    size: 'L',
    colour: 'Gloss Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Aerodynamic energy-impact thermoplastic shell helmet with Pinlock-ready visor, breath deflector, and removable hypoallergenic liner.',
    imageUrl: '',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-102',
    productName: 'LS2 FF353 Rapid Solid Matte Black',
    brand: 'LS2',
    model: 'Rapid FF353',
    sku: 'LS2-101',
    barcode: '890123400002',
    purchasePrice: 5100,
    wholesalePrice: 6100,
    salePrice: 7200,
    stockLevel: 4,
    reorderPoint: 8,
    maxStock: 40,
    weight: '1300g',
    size: 'M',
    colour: 'Matte Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Ultra-light HPTT composite shell with quick release visor system, dynamic flow-through ventilation, and breath guard.',
    imageUrl: '',
    createdAt: '2026-07-03T11:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-103',
    productName: 'Axor Apex Venom Neon Yellow',
    brand: 'Axor',
    model: 'Apex Venom',
    sku: 'AX-201',
    barcode: '890123400003',
    purchasePrice: 4800,
    wholesalePrice: 5600,
    salePrice: 6500,
    stockLevel: 24,
    reorderPoint: 8,
    maxStock: 60,
    weight: '1500g',
    size: 'XL',
    colour: 'Neon Yellow / Black',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'ECE 22.05 & DOT certified aggressive graphic helmet featuring integrated dual-visor system and chin curtain.',
    imageUrl: '',
    createdAt: '2026-07-05T09:30:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-104',
    productName: 'Steelbird SBA-7 7SEVEN Flip-Up',
    brand: 'Steelbird',
    model: 'SBA-7 7SEVEN',
    sku: 'SB-301',
    barcode: '890123400004',
    purchasePrice: 2600,
    wholesalePrice: 3100,
    salePrice: 3799,
    stockLevel: 0,
    reorderPoint: 6,
    maxStock: 35,
    weight: '1400g',
    size: 'L',
    colour: 'Titanium Grey',
    category: 'Modular',
    gearType: 'Helmets',
    description: 'Versatile modular flip-up helmet with high-impact engineering ABS casing, micro-metric buckle, and anti-scratch visor.',
    imageUrl: '',
    createdAt: '2026-07-08T14:15:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-105',
    productName: 'MT Helmets Thunder 4 SV Solid',
    brand: 'MT',
    model: 'Thunder 4 SV',
    sku: 'MT-401',
    barcode: '890123400005',
    purchasePrice: 7500,
    wholesalePrice: 8800,
    salePrice: 9900,
    stockLevel: 12,
    reorderPoint: 4,
    maxStock: 25,
    weight: '1550g',
    size: 'M',
    colour: 'Pearl White',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'ECE 22.06 certified next-generation touring helmet with internal drop-down sun visor and emergency release cheek pads.',
    imageUrl: '',
    createdAt: '2026-07-10T16:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-106',
    productName: 'Studds Thunder D1 Open Face',
    brand: 'Studds',
    model: 'Thunder D1',
    sku: 'ST-501',
    barcode: '890123400006',
    purchasePrice: 1400,
    wholesalePrice: 1750,
    salePrice: 2150,
    stockLevel: 35,
    reorderPoint: 10,
    maxStock: 80,
    weight: '980g',
    size: 'M',
    colour: 'Matt Blue',
    category: 'Open Face',
    gearType: 'Helmets',
    description: 'Lightweight urban commuter helmet with high-density EPS liner, wide peripheral vision, and quick-release strap.',
    imageUrl: '',
    createdAt: '2026-07-12T12:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-107',
    productName: 'AGV K1 S Speed Red',
    brand: 'AGV',
    model: 'K1 S',
    sku: 'AGV-601',
    barcode: '890123400007',
    purchasePrice: 18500,
    wholesalePrice: 21000,
    salePrice: 24500,
    stockLevel: 5,
    reorderPoint: 3,
    maxStock: 15,
    weight: '1500g',
    size: 'L',
    colour: 'Speed Red / Black',
    category: 'Dual Sport',
    gearType: 'Helmets',
    description: 'MotoGP-derived aero spoiler, high-resistance thermoplastic shell, and 190° horizontal field of vision.',
    imageUrl: '',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-108',
    productName: 'Arai Tour-X4 Adventure Matte White',
    brand: 'Arai',
    model: 'Tour-X4',
    sku: 'AR-701',
    barcode: '890123400008',
    purchasePrice: 42000,
    wholesalePrice: 48000,
    salePrice: 55000,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 10,
    weight: '1620g',
    size: 'XL',
    colour: 'Matte White',
    category: 'Adventure',
    gearType: 'Helmets',
    description: 'Flagship adventure helmet built with Super Complex Laminate Construction (SCLC) for unmatched impact protection.',
    imageUrl: '',
    createdAt: '2026-07-20T14:30:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  },
  {
    id: 'hlm-109',
    productName: 'HJC RPHA 11 Carbon Solid',
    brand: 'HJC',
    model: 'RPHA 11',
    sku: 'HJC-801',
    barcode: '890123400009',
    purchasePrice: 28000,
    wholesalePrice: 32000,
    salePrice: 36500,
    stockLevel: 8,
    reorderPoint: 3,
    maxStock: 20,
    weight: '1250g',
    size: 'L',
    colour: 'Carbon Weave',
    category: 'Full Face',
    gearType: 'Helmets',
    description: 'Full Carbon Fiber Outer Shell racing helmet with RapidFire II visor replacement system and max airflow ventilation.',
    imageUrl: '',
    createdAt: '2026-07-22T08:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z'
  }
];


export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Brake System', description: 'Disc pads, calipers, rotors, brake lines, and master cylinders.' },
  { id: 'cat-2', name: 'Engine Parts', description: 'Pistons, rings, valves, gaskets, filters, and spark plugs.' },
  { id: 'cat-3', name: 'Electrical', description: 'Stators, CDI units, wiring harnesses, starter motors, and batteries.' },
  { id: 'cat-4', name: 'Transmission', description: 'Chains, sprockets, clutches, gearbox gears, and belts.' },
  { id: 'cat-5', name: 'Suspension', description: 'Fork seals, shock absorbers, swingarms, and linkages.' },
  { id: 'cat-6', name: 'Filters', description: 'Air filters, oil filters, fuel filters.' },
  { id: 'cat-7', name: 'Wheels', description: 'Tires, rims, spokes, bearings, and axles.' },
  { id: 'cat-8', name: 'Body Parts', description: 'Fairings, mudguards, mirrors, frames.' },
  { id: 'cat-9', name: 'Accessories', description: 'Luggage racks, phone mounts, crash guards.' },
  { id: 'cat-10', name: 'Lubricants', description: 'Engine oil, chain lube, brake fluid, coolant.' },
  { id: 'cat-11', name: 'Others', description: 'General nuts, bolts, and miscellaneous washers.' },
  { id: 'cat-12', name: 'Control Cables', description: 'Accelerator, clutch, brake, and speedometer cables.' }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup-1', name: 'Nippon Performance Parts', email: 'orders@nipponparts.jp', phone: '+81-3-5555-0192', contactPerson: 'Takeshi Sato', leadTimeDays: 7 },
  { id: 'sup-2', name: 'Brembo Racing Supply', email: 'wholesale@bremboracing.it', phone: '+39-035-123456', contactPerson: 'Luca Rossi', leadTimeDays: 14 },
  { id: 'sup-3', name: 'Apex Drive Logistics', email: 'sales@apexdrive.com', phone: '+1-800-555-0143', contactPerson: 'Sarah Jenkins', leadTimeDays: 5 },
  { id: 'sup-4', name: 'MotoShield Electricals', email: 'support@motoshield.tw', phone: '+886-2-2777-1234', contactPerson: 'David Chen', leadTimeDays: 10 }
];

export const INITIAL_VEHICLES: VehicleModel[] = [
  { id: 'veh-1', make: 'Yamaha', model: 'YZF-R1', year: '2020-2024', engineCC: '998cc' },
  { id: 'veh-2', make: 'Honda', model: 'CB500X', year: '2019-2023', engineCC: '471cc' },
  { id: 'veh-3', make: 'Kawasaki', model: 'Ninja 400', year: '2018-2024', engineCC: '399cc' },
  { id: 'veh-4', make: 'Suzuki', model: 'V-Strom 650', year: '2017-2023', engineCC: '645cc' },
  { id: 'veh-5', make: 'KTM', model: 'Duke 390', year: '2020-2024', engineCC: '373cc' },
  { id: 'veh-6', make: 'Bajaj', model: 'Pulsar 150', year: '2015-2024', engineCC: '149.5cc' },
  { id: 'veh-7', make: 'Bajaj', model: 'Pulsar 180', year: '2015-2023', engineCC: '178.6cc' },
  { id: 'veh-8', make: 'Bajaj', model: 'Pulsar 220', year: '2016-2024', engineCC: '220cc' },
  { id: 'veh-9', make: 'Bajaj', model: 'Discover 150', year: '2014-2020', engineCC: '144.8cc' },
  { id: 'veh-10', make: 'TVS', model: 'Apache 200', year: '2018-2024', engineCC: '197.7cc' },
  { id: 'veh-11', make: 'Yamaha', model: 'FZSv3', year: '2019-2024', engineCC: '149cc' },
  { id: 'veh-12', make: 'Yamaha', model: 'FZS V4', year: '2023-2025', engineCC: '149cc' },
  { id: 'veh-13', make: 'Yamaha', model: 'Rayz', year: '2018-2024', engineCC: '125cc' },
  { id: 'veh-14', make: 'Honda', model: 'Dio', year: '2017-2024', engineCC: '109.5cc' },
  { id: 'veh-15', make: 'KTM', model: 'Duke 200', year: '2018-2024', engineCC: '199.5cc' },
  { id: 'veh-16', make: 'KTM', model: 'Duke 250', year: '2019-2024', engineCC: '248.8cc' },
  { id: 'veh-17', make: 'Royal Enfield', model: 'Bullet 350', year: '2016-2024', engineCC: '349cc' },
  { id: 'veh-18', make: 'Hero', model: 'Super Splendor', year: '2015-2024', engineCC: '125cc' },
  { id: 'veh-19', make: 'Bajaj', model: 'Pulsar NS200', year: '2012-2024', engineCC: '199.5cc' },
  { id: 'veh-20', make: 'Bajaj', model: 'Discover 125', year: '2011-2020', engineCC: '124.5cc' },
  { id: 'veh-21', make: 'Bajaj', model: 'Discover 100', year: '2009-2015', engineCC: '94.3cc' },
  { id: 'veh-22', make: 'Honda', model: 'CB Hornet / Trigger', year: '2015-2022', engineCC: '162.7cc' },
  { id: 'veh-23', make: 'TVS', model: 'Apache RTR 160 4V', year: '2018-2024', engineCC: '159.7cc' },
  { id: 'veh-24', make: 'Honda', model: 'CB Shine', year: '2015-2024', engineCC: '124cc' },
  { id: 'veh-25', make: 'TVS', model: 'NTorq 125', year: '2018-2024', engineCC: '124.8cc' },
  { id: 'veh-26', make: 'Yamaha', model: 'Fascino 125 FI', year: '2020-2024', engineCC: '125cc' },
  { id: 'veh-27', make: 'Hero', model: 'Glamour', year: '2014-2024', engineCC: '124.7cc' },
  { id: 'veh-28', make: 'Honda', model: 'Unicorn 150/160', year: '2010-2024', engineCC: '162.7cc' },
  { id: 'veh-29', make: 'Yamaha', model: 'Saluto 125', year: '2015-2022', engineCC: '125cc' }
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'part-1', sku: 'BRK-PAD-YAM-001', name: 'Brembo Sintered Front Brake Pads',
    oemNumber: '4B8-W0045-00-00', categoryId: 'cat-1', supplierId: 'sup-2',
    costPrice: 42.50, wholesalePrice: 62.00, salePrice: 79.99,
    stockLevel: 14, reorderPoint: 15, maxStock: 100, unit: 'Set', binLocation: 'A-12-04',
    description: 'High-performance sintered brake pads for outstanding stopping power in both wet and dry conditions.',
    brand: 'Yamaha', barcode: '743210984321', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-1', 'veh-3']
  },
  {
    id: 'part-2', sku: 'ENG-PIS-HON-052', name: 'Honda OEM Piston Ring Set (STD)',
    oemNumber: '13011-MKP-D01', categoryId: 'cat-2', supplierId: 'sup-1',
    costPrice: 28.00, wholesalePrice: 38.50, salePrice: 49.95,
    stockLevel: 4, reorderPoint: 5, maxStock: 50, unit: 'Set', binLocation: 'B-03-11',
    description: 'Genuine Honda standard-size replacement piston rings. Pack of 2.',
    brand: 'Honda', barcode: '490250800123', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-2']
  },
  {
    id: 'part-3', sku: 'ELE-CDI-KAW-809', name: 'MotoShield Digital CDI Unit',
    oemNumber: '21119-0084', categoryId: 'cat-3', supplierId: 'sup-4',
    costPrice: 85.00, wholesalePrice: 125.00, salePrice: 159.00,
    stockLevel: 3, reorderPoint: 3, maxStock: 20, unit: 'Pcs', binLocation: 'C-01-02',
    description: 'Advanced microchip-controlled CDI unit with optimized ignition curves.',
    brand: 'Kawasaki', barcode: '071234567890', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-3']
  },
  {
    id: 'part-4', sku: 'DRV-CHN-DID-520', name: 'DID 520 VX3 Pro-Street X-Ring Chain',
    oemNumber: 'DID-520-VX3-120', categoryId: 'cat-4', supplierId: 'sup-3',
    costPrice: 55.00, wholesalePrice: 78.00, salePrice: 99.50,
    stockLevel: 25, reorderPoint: 10, maxStock: 150, unit: 'Pcs', binLocation: 'D-08-01',
    description: 'Gold & Black extreme longevity chain. 120 Links. Features patented X-ring sealing technology.',
    brand: 'Others', barcode: '880123456789', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-1', 'veh-2', 'veh-3', 'veh-4', 'veh-5']
  },
  {
    id: 'part-5', sku: 'SUS-FSE-NOK-041', name: 'NOK Fork Seal Kit 41mm',
    oemNumber: '51153-14D00', categoryId: 'cat-5', supplierId: 'sup-1',
    costPrice: 12.00, wholesalePrice: 18.00, salePrice: 24.99,
    stockLevel: 30, reorderPoint: 12, maxStock: 200, unit: 'Set', binLocation: 'A-02-15',
    description: 'Japanese-made premium fork seals and dust covers. Kit contains seals for both fork legs.',
    brand: 'Suzuki', barcode: '497123456789', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-2', 'veh-4']
  },
  {
    id: 'part-6', sku: 'ENG-FLT-KNE-044', name: 'K&N Premium Oil Filter KN-204',
    oemNumber: 'KN-204-C', categoryId: 'cat-6', supplierId: 'sup-3',
    costPrice: 7.50, wholesalePrice: 12.00, salePrice: 16.95,
    stockLevel: 45, reorderPoint: 20, maxStock: 300, unit: 'Pcs', binLocation: 'B-01-04',
    description: 'High-flow oil filter with heavy-duty construction and 17mm hex nut for easy removal.',
    brand: 'Honda', barcode: '024844002046', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-1', 'veh-2', 'veh-3', 'veh-4']
  },
  {
    id: 'part-7', sku: 'ENG-SPK-NGK-009', name: 'NGK Laser Iridium Spark Plug LMAR8A-9',
    oemNumber: 'NGK-LMAR8A9', categoryId: 'cat-2', supplierId: 'sup-1',
    costPrice: 9.80, wholesalePrice: 14.50, salePrice: 19.99,
    stockLevel: 62, reorderPoint: 30, maxStock: 500, unit: 'Pcs', binLocation: 'B-02-09',
    description: 'Laser iridium tipped spark plug for extreme combustion efficiency and longer life.',
    brand: 'KTM', barcode: '087295948911', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-1', 'veh-2', 'veh-5']
  },
  {
    id: 'part-8', sku: 'DRV-SPR-JTR-130', name: 'JT Rear Steel Sprocket 45T',
    oemNumber: 'JTR1304.45', categoryId: 'cat-4', supplierId: 'sup-3',
    costPrice: 22.00, wholesalePrice: 31.00, salePrice: 42.50,
    stockLevel: 8, reorderPoint: 8, maxStock: 40, unit: 'Pcs', binLocation: 'D-02-04',
    description: 'High-carbon steel rear sprocket. 45 teeth, 520 pitch.',
    brand: 'Bajaj', barcode: '501234567890', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-2', 'veh-5']
  },
  {
    id: 'part-9', sku: 'ELE-BAT-YUA-012', name: 'Yuasa YTZ10S Factory Activated Battery',
    oemNumber: 'YTZ10S-BS', categoryId: 'cat-3', supplierId: 'sup-4',
    costPrice: 65.00, wholesalePrice: 92.00, salePrice: 119.99,
    stockLevel: 0, reorderPoint: 6, maxStock: 30, unit: 'Pcs', binLocation: 'C-04-10',
    description: 'Absorbed Glass Mat (AGM) high-performance maintenance-free battery. Spillsafe design.',
    brand: 'Yamaha', barcode: '497665012345', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-1', 'veh-5']
  },
  {
    id: 'part-10', sku: 'SUS-SHK-YSS-456', name: 'YSS Top-Line Mono Shock Absorber',
    oemNumber: 'MZ456-310TRL', categoryId: 'cat-5', supplierId: 'sup-1',
    costPrice: 240.00, wholesalePrice: 325.00, salePrice: 419.00,
    stockLevel: 2, reorderPoint: 2, maxStock: 10, unit: 'Pcs', binLocation: 'E-01-02',
    description: 'Gas-charged rear monoshock with rebound, preload, and length adjustments.',
    brand: 'Suzuki', barcode: '885871234567', imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-2', 'veh-4']
  },
  {
    id: 'cab-acc-1',
    sku: 'CAB-ACC-HRO-SPL',
    name: 'ACC Cable Super Splendor / Glamour',
    oemNumber: 'OEM-HRO-ACC-SPL',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 29,
    reorderPoint: 5,
    maxStock: 50,
    unit: 'Pcs',
    binLocation: 'CAB-01',
    description: 'Accelerator cable for Hero Super Splendor and Hero Glamour.',
    brand: 'Hero',
    barcode: '890100100001',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-18', 'veh-27']
  },
  {
    id: 'cab-acc-2',
    sku: 'CAB-ACC-BAJ-NS200-CARB',
    name: 'ACC Cable Pulsar NS 200 Carburetor',
    oemNumber: 'OEM-BAJ-ACC-NS200C',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-02',
    description: 'Accelerator cable for Bajaj Pulsar 200 NS / NS 200 (Carburetor version).',
    brand: 'Bajaj',
    barcode: '890100100002',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-3',
    sku: 'CAB-ACC-BAJ-NS200-FI',
    name: 'ACC Cable NS 200cc FI',
    oemNumber: 'OEM-BAJ-ACC-NS200FI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-03',
    description: 'Accelerator cable for Bajaj Pulsar NS 200 (Fuel Injection version).',
    brand: 'Bajaj',
    barcode: '890100100003',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-19']
  },
  {
    id: 'cab-acc-4',
    sku: 'CAB-ACC-BAJ-P220',
    name: 'ACC Cable 220 Pulsar',
    oemNumber: 'OEM-BAJ-ACC-P220',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 19,
    reorderPoint: 5,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-04',
    description: 'Accelerator cable for Bajaj Pulsar 220 / 220F.',
    brand: 'Bajaj',
    barcode: '890100100004',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-8']
  },
  {
    id: 'cab-acc-5',
    sku: 'CAB-ACC-BAJ-DIS125-NEW',
    name: 'ACC Cable Discover 125cc New',
    oemNumber: 'OEM-BAJ-ACC-D125N',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 4,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-05',
    description: 'Accelerator cable for Bajaj Discover 125 (New model).',
    brand: 'Bajaj',
    barcode: '890100100005',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-6',
    sku: 'CAB-ACC-BAJ-P150',
    name: 'ACC Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-ACC-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-06',
    description: 'Accelerator cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100006',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-7',
    sku: 'CAB-ACC-HON-HOR-TRIG',
    name: 'ACC Cable Hornet/Trigger',
    oemNumber: 'OEM-HON-ACC-HT160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-07',
    description: 'Accelerator cable for Honda CB Hornet 160R / CB Trigger.',
    brand: 'Honda',
    barcode: '890100100007',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-22']
  },
  {
    id: 'cab-acc-8',
    sku: 'CAB-ACC-TVS-RTR160-4V',
    name: 'ACC Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-ACC-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-08',
    description: 'Accelerator cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100008',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-acc-9',
    sku: 'CAB-ACC-BAJ-DIS100-125M',
    name: 'ACC Cable Discover 100cc/Discover 125M',
    oemNumber: 'OEM-BAJ-ACC-D100M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-09',
    description: 'Accelerator cable for Bajaj Discover 100cc / Discover 125M.',
    brand: 'Bajaj',
    barcode: '890100100009',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20', 'veh-21']
  },
  {
    id: 'cab-clu-1',
    sku: 'CAB-CLU-TVS-RTR160-4V',
    name: 'Clutch Cable RTR 160cc 4V',
    oemNumber: 'OEM-TVS-CLU-RTR1604V',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 2,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-10',
    description: 'Clutch control cable for TVS Apache RTR 160 4V.',
    brand: 'TVS',
    barcode: '890100100010',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-23']
  },
  {
    id: 'cab-clu-2',
    sku: 'CAB-CLU-BAJ-P150',
    name: 'Clutch Cable Pulsar 150cc',
    oemNumber: 'OEM-BAJ-CLU-P150',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 3,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-11',
    description: 'Clutch control cable for Bajaj Pulsar 150.',
    brand: 'Bajaj',
    barcode: '890100100011',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-6']
  },
  {
    id: 'cab-acc-10',
    sku: 'CAB-ACC-BAJ-DIS125-OLD',
    name: 'ACC Cable Discover 125cc Old',
    oemNumber: 'OEM-BAJ-ACC-D125O',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 3,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-12',
    description: 'Accelerator cable for Bajaj Discover 125 (Old model).',
    brand: 'Bajaj',
    barcode: '890100100012',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-11',
    sku: 'CAB-ACC-BAJ-DIS125-ST',
    name: 'ACC Cable Discover 125 ST',
    oemNumber: 'OEM-BAJ-ACC-D125ST',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-13',
    description: 'Accelerator cable for Bajaj Discover 125 ST.',
    brand: 'Bajaj',
    barcode: '890100100013',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-12',
    sku: 'CAB-ACC-BAJ-DIS125-M',
    name: 'ACC Cable Discover 125 M',
    oemNumber: 'OEM-BAJ-ACC-D125M',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 14,
    reorderPoint: 4,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-14',
    description: 'Accelerator cable for Bajaj Discover 125 M.',
    brand: 'Bajaj',
    barcode: '890100100014',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-20']
  },
  {
    id: 'cab-acc-13',
    sku: 'CAB-ACC-HON-SHINE',
    name: 'ACC Cable Honda Shine',
    oemNumber: 'OEM-HON-ACC-SHINE',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 15,
    reorderPoint: 4,
    maxStock: 40,
    unit: 'Pcs',
    binLocation: 'CAB-15',
    description: 'Accelerator cable for Honda CB Shine 125.',
    brand: 'Honda',
    barcode: '890100100015',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-24']
  },
  {
    id: 'cab-acc-14',
    sku: 'CAB-ACC-YAM-FZV3-FI',
    name: 'ACC Cable Yamaha FZ V3 / FZ-FI / FZS-FI',
    oemNumber: 'OEM-YAM-ACC-FZV3',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 9,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-16',
    description: 'Accelerator cable for Yamaha FZ V3, FZ-FI, and FZS-FI.',
    brand: 'Yamaha',
    barcode: '890100100016',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-11', 'veh-12']
  },
  {
    id: 'cab-acc-15',
    sku: 'CAB-ACC-TVS-NTORQ-BS6',
    name: 'ACC Cable TVS NTORQ BS6 FI',
    oemNumber: 'OEM-TVS-ACC-NTORQ6',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-17',
    description: 'Accelerator cable for TVS NTORQ 125 BS-6 FI.',
    brand: 'TVS',
    barcode: '890100100017',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-25']
  },
  {
    id: 'cab-acc-16',
    sku: 'CAB-ACC-YAM-FASC-RAYZR',
    name: 'ACC Cable Yamaha Fascino 125 FI / Ray-ZR 125',
    oemNumber: 'OEM-YAM-ACC-F125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 6,
    reorderPoint: 2,
    maxStock: 25,
    unit: 'Pcs',
    binLocation: 'CAB-18',
    description: 'Accelerator cable for Yamaha Fascino 125 FI and Ray-ZR 125 FI.',
    brand: 'Yamaha',
    barcode: '890100100018',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-13', 'veh-26']
  },
  {
    id: 'cab-acc-17',
    sku: 'CAB-ACC-HRO-GLM-FI',
    name: 'ACC Cable Hero Glamour FI',
    oemNumber: 'OEM-HRO-ACC-GLMFI',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-19',
    description: 'Accelerator cable for Hero Glamour FI (Fuel Injection model).',
    brand: 'Hero',
    barcode: '890100100019',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-27']
  },
  {
    id: 'cab-acc-18',
    sku: 'CAB-ACC-HON-UNICORN',
    name: 'ACC Cable Honda Unicorn',
    oemNumber: 'OEM-HON-ACC-UNI160',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 10,
    reorderPoint: 3,
    maxStock: 30,
    unit: 'Pcs',
    binLocation: 'CAB-20',
    description: 'Accelerator cable for Honda Unicorn 150 / 160.',
    brand: 'Honda',
    barcode: '890100100020',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-28']
  },
  {
    id: 'cab-acc-19',
    sku: 'CAB-ACC-YAM-SALUTO',
    name: 'ACC Cable Yamaha Saluto',
    oemNumber: 'OEM-YAM-ACC-SAL125',
    categoryId: 'cat-12',
    supplierId: '',
    costPrice: 0,
    wholesalePrice: 0,
    salePrice: 0,
    stockLevel: 5,
    reorderPoint: 2,
    maxStock: 20,
    unit: 'Pcs',
    binLocation: 'CAB-21',
    description: 'Accelerator cable for Yamaha Saluto 125.',
    brand: 'Yamaha',
    barcode: '890100100021',
    imageUrl: '/parts_thumbnail.png',
    compatibilityIds: ['veh-29']
  }
];

// ─── Sales Orders & Items ─────────────────────────────────────────────────────
export const INITIAL_SALES_ORDERS: SalesOrder[] = [];
export const INITIAL_SALES_ORDER_ITEMS: SalesOrderItem[] = [];


// ─── 12-Month Rich Purchase Order History ─────────────────────────────────────
export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  // Aug 2025
  { id: 'po-001', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2025-08-01', expectedDelivery: '2025-08-15', totalAmount: 850.00 },
  { id: 'po-002', supplierId: 'sup-1', status: 'RECEIVED', orderDate: '2025-08-20', expectedDelivery: '2025-08-27', totalAmount: 490.00 },
  // Sep 2025
  { id: 'po-003', supplierId: 'sup-3', status: 'RECEIVED', orderDate: '2025-09-05', expectedDelivery: '2025-09-10', totalAmount: 1100.00 },
  { id: 'po-004', supplierId: 'sup-4', status: 'RECEIVED', orderDate: '2025-09-22', expectedDelivery: '2025-10-02', totalAmount: 650.00 },
  // Oct 2025
  { id: 'po-005', supplierId: 'sup-1', status: 'RECEIVED', orderDate: '2025-10-08', expectedDelivery: '2025-10-15', totalAmount: 756.00 },
  { id: 'po-006', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2025-10-25', expectedDelivery: '2025-11-08', totalAmount: 425.00 },
  // Nov 2025
  { id: 'po-007', supplierId: 'sup-3', status: 'RECEIVED', orderDate: '2025-11-10', expectedDelivery: '2025-11-15', totalAmount: 2200.00 },
  { id: 'po-008', supplierId: 'sup-4', status: 'RECEIVED', orderDate: '2025-11-28', expectedDelivery: '2025-12-08', totalAmount: 780.00 },
  // Dec 2025
  { id: 'po-009', supplierId: 'sup-1', status: 'RECEIVED', orderDate: '2025-12-02', expectedDelivery: '2025-12-09', totalAmount: 980.00 },
  { id: 'po-010', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2025-12-15', expectedDelivery: '2025-12-29', totalAmount: 850.00 },
  // Jan 2026
  { id: 'po-011', supplierId: 'sup-3', status: 'RECEIVED', orderDate: '2026-01-07', expectedDelivery: '2026-01-12', totalAmount: 660.00 },
  { id: 'po-012', supplierId: 'sup-4', status: 'RECEIVED', orderDate: '2026-01-20', expectedDelivery: '2026-01-30', totalAmount: 1040.00 },
  // Feb 2026
  { id: 'po-013', supplierId: 'sup-1', status: 'RECEIVED', orderDate: '2026-02-03', expectedDelivery: '2026-02-10', totalAmount: 588.00 },
  // Mar 2026
  { id: 'po-014', supplierId: 'sup-3', status: 'RECEIVED', orderDate: '2026-03-10', expectedDelivery: '2026-03-15', totalAmount: 3300.00 },
  { id: 'po-015', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2026-03-25', expectedDelivery: '2026-04-08', totalAmount: 680.00 },
  // Apr 2026
  { id: 'po-016', supplierId: 'sup-4', status: 'RECEIVED', orderDate: '2026-04-12', expectedDelivery: '2026-04-22', totalAmount: 1300.00 },
  // May 2026
  { id: 'po-017', supplierId: 'sup-1', status: 'RECEIVED', orderDate: '2026-05-05', expectedDelivery: '2026-05-12', totalAmount: 880.00 },
  { id: 'po-018', supplierId: 'sup-3', status: 'RECEIVED', orderDate: '2026-05-20', expectedDelivery: '2026-05-25', totalAmount: 4400.00 },
  // Jun 2026
  { id: 'po-019', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2026-06-08', expectedDelivery: '2026-06-22', totalAmount: 850.00 },
  { id: 'po-020', supplierId: 'sup-4', status: 'RECEIVED', orderDate: '2026-06-20', expectedDelivery: '2026-06-30', totalAmount: 1950.00 },
  // Jul 2026 (current)
  { id: 'po-101', supplierId: 'sup-2', status: 'RECEIVED', orderDate: '2026-07-02', expectedDelivery: '2026-07-16', totalAmount: 425.00 },
  { id: 'po-102', supplierId: 'sup-4', status: 'SENT', orderDate: '2026-07-12', expectedDelivery: '2026-07-22', totalAmount: 1040.00 },
  { id: 'po-103', supplierId: 'sup-1', status: 'DRAFT', orderDate: '2026-07-17', expectedDelivery: '2026-07-24', totalAmount: 396.00 }
];

export const INITIAL_PURCHASE_ORDER_ITEMS: PurchaseOrderItem[] = [
  { id: 'poi-1', orderId: 'po-101', partId: 'part-1', quantity: 10, unitCost: 42.50 },
  { id: 'poi-2', orderId: 'po-102', partId: 'part-9', quantity: 16, unitCost: 65.00 },
  { id: 'poi-3', orderId: 'po-103', partId: 'part-2', quantity: 10, unitCost: 28.00 },
  { id: 'poi-4', orderId: 'po-103', partId: 'part-7', quantity: 10, unitCost: 9.80 }
];

// ─── Phase 2: Seeding logs ───────────────────────────────────────────────────
export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  { id: 'sm-1', partId: 'part-1', type: 'MANUAL_ADJUST', quantity: 6, timestamp: '2026-07-01T10:00:00Z', referenceId: 'MANUAL', notes: 'Initial stock load adjustment' },
  { id: 'sm-2', partId: 'part-1', type: 'PO_RECEIVED', quantity: 10, timestamp: '2026-07-16T15:30:00Z', referenceId: 'po-101', notes: 'Received Restock PO' },
  { id: 'sm-4', partId: 'part-2', type: 'MANUAL_ADJUST', quantity: 4, timestamp: '2026-07-02T11:00:00Z', referenceId: 'MANUAL', notes: 'Stock counting correction' },
  { id: 'sm-5', partId: 'part-9', type: 'MANUAL_ADJUST', quantity: 0, timestamp: '2026-07-03T14:00:00Z', referenceId: 'MANUAL', notes: 'Marked as out of stock' }
];

export const INITIAL_HISTORY_LOGS: ProductHistoryLog[] = [
  { id: 'ph-1', partId: 'part-1', changeType: 'CREATED', timestamp: '2026-07-01T09:00:00Z', user: 'Pankaj.ydv707@gmail.com', details: 'Part catalogued in system database.' },
  { id: 'ph-2', partId: 'part-1', changeType: 'EDITED', timestamp: '2026-07-05T12:00:00Z', user: 'Pankaj.ydv707@gmail.com', details: 'Updated Bin Location from B-12 to A-12-04.' },
  { id: 'ph-3', partId: 'part-2', changeType: 'CREATED', timestamp: '2026-07-02T10:30:00Z', user: 'Pankaj.ydv707@gmail.com', details: 'Part catalogued in system database.' }
];

// ─── Phase 4: Customers ───────────────────────────────────────────────────────
export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'cust-1', name: 'DownTown Moto Workshop', email: 'orders@dtmoto.com', phone: '+60-3-2145-6789', address: '12 Jalan Bukit Bintang, Kuala Lumpur', type: 'TRADE', notes: 'Primary trade customer. Net-30 credit terms.', createdAt: '2026-01-15T09:00:00Z' },
  { id: 'cust-2', name: 'SpeedKings Racing', email: 'parts@speedkings.my', phone: '+60-4-7123-4567', address: '88 Jalan Raja Laut, Penang', type: 'WHOLESALE', notes: 'Bulk orders for racing season. Priority customer.', createdAt: '2026-02-01T10:30:00Z' },
  { id: 'cust-3', name: 'Ahmad Faruqi', email: 'ahmad.faruqi@gmail.com', phone: '+60-12-345-6789', address: '45 Taman Melati, Ampang', type: 'RETAIL', notes: 'Regular retail buyer. Honda CB500X enthusiast.', createdAt: '2026-03-10T14:00:00Z' },
  { id: 'cust-4', name: 'MotoFix Garage Klang', email: 'motofix.klang@gmail.com', phone: '+60-3-3371-9900', address: '7 Jalan Meru, Klang', type: 'TRADE', notes: 'Workshop specializing in Kawasaki & Suzuki.', createdAt: '2026-04-05T11:00:00Z' },
  { id: 'cust-5', name: 'Hafiz Motorsports', email: 'hafiz@hafizmotors.com', phone: '+60-11-2233-4455', address: '23 Jalan Cheras, Kuala Lumpur', type: 'WHOLESALE', notes: 'Preferred wholesale discount 15%.', createdAt: '2026-05-20T09:00:00Z' },
  { id: 'cust-6', name: 'Lee Ming Parts Sdn Bhd', email: 'lee.ming@leeparts.com.my', phone: '+60-3-7887-1122', address: '55 Jalan SS2, Petaling Jaya', type: 'TRADE', notes: 'Premium trade partner.', createdAt: '2026-06-01T08:00:00Z' }
];

// ─── Phase 4: Returns ────────────────────────────────────────────────────────
export const INITIAL_RETURNS: Return[] = [];

// ─── Phase 4: Damaged Stock ───────────────────────────────────────────────────
export const INITIAL_DAMAGED_STOCK: DamagedStock[] = [
  {
    id: 'dmg-1',
    reportNumber: 'DMG-2026-00001',
    partId: 'part-3',
    partName: 'NGK Iridium Spark Plug CR9EIX',
    quantity: 2,
    reason: 'Received broken from supplier packaging - transit damage.',
    reportedBy: 'Pankaj.ydv707@gmail.com',
    timestamp: '2026-07-05T10:00:00Z',
    resolved: true,
    estimatedLoss: 34.00
  }
];

// ─── Phase 4: Stock Adjustments ───────────────────────────────────────────────
export const INITIAL_STOCK_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: 'adj-1',
    adjustmentNumber: 'ADJ-2026-00001',
    partId: 'part-1',
    partName: 'Brembo Sintered Front Brake Pads',
    previousQty: 10,
    adjustedQty: 14,
    delta: 4,
    reason: 'Physical stock count discrepancy corrected after quarterly audit.',
    type: 'ADDITION',
    adjustedBy: 'Pankaj.ydv707@gmail.com',
    timestamp: '2026-07-01T09:30:00Z'
  },
  {
    id: 'adj-2',
    adjustmentNumber: 'ADJ-2026-00002',
    partId: 'part-4',
    partName: 'KTM Stator Coil Generator',
    previousQty: 5,
    adjustedQty: 4,
    delta: -1,
    reason: 'Write-off — display unit used for showroom demo.',
    type: 'REDUCTION',
    adjustedBy: 'Pankaj.ydv707@gmail.com',
    timestamp: '2026-07-08T15:00:00Z'
  }
];

// ─── Phase 4: Notifications ───────────────────────────────────────────────────
export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'LOW_STOCK',
    title: 'Restock Soon',
    message: 'Brembo Sintered Front Brake Pads (BRK-PAD-YAM-001) is below reorder point. Current: 14, Min: 15.',
    referenceId: 'part-1',
    isRead: false,
    createdAt: '2026-07-18T08:00:00Z',
    priority: 'HIGH',
    navigateTo: 'inventory'
  },
  {
    id: 'notif-2',
    type: 'OUT_OF_STOCK',
    title: 'Out of Stock Items — Immediate Attention Required',
    message: 'KTM Stator Coil Generator (ELC-STA-KTM-009) is completely out of stock. Immediate reorder required.',
    referenceId: 'part-9',
    isRead: false,
    createdAt: '2026-07-17T14:30:00Z',
    priority: 'HIGH',
    navigateTo: 'inventory'
  },
  {
    id: 'notif-3',
    type: 'NEW_SALE',
    title: 'New Sale Created',
    message: 'Invoice recorded for SpeedKings Racing — $2,450.00. Order #so-215.',
    referenceId: 'so-215',
    isRead: false,
    createdAt: '2026-07-18T10:15:00Z',
    priority: 'LOW',
    navigateTo: 'sales'
  },
  {
    id: 'notif-4',
    type: 'PO_DELIVERY',
    title: 'Purchase Order Received',
    message: 'PO #po-101 from Brembo Racing Supply received. 10 items restocked to inventory.',
    referenceId: 'po-101',
    isRead: true,
    createdAt: '2026-07-16T15:30:00Z',
    priority: 'MEDIUM',
    navigateTo: 'suppliers'
  },
  {
    id: 'notif-5',
    type: 'RETURN',
    title: 'Return Request Approved',
    message: 'RET-2026-00001 from DownTown Moto Workshop processed. 1 × Brake Pads restocked.',
    referenceId: 'ret-1',
    isRead: true,
    createdAt: '2026-07-10T14:00:00Z',
    priority: 'MEDIUM',
    navigateTo: 'returns'
  },
  {
    id: 'notif-6',
    type: 'DAMAGED_STOCK',
    title: 'Damaged Stock Reported',
    message: 'DMG-2026-00001: 2× NGK Iridium Spark Plugs written off. Estimated loss: $34.00.',
    referenceId: 'dmg-1',
    isRead: true,
    createdAt: '2026-07-05T10:00:00Z',
    priority: 'MEDIUM',
    navigateTo: 'returns'
  },
  {
    id: 'notif-7',
    type: 'STOCK_ADJUST',
    title: 'Stock Adjustment Applied',
    message: 'ADJ-2026-00001: Brembo Brake Pads adjusted +4 units after quarterly audit. New stock: 14.',
    referenceId: 'adj-1',
    isRead: true,
    createdAt: '2026-07-01T09:30:00Z',
    priority: 'LOW',
    navigateTo: 'returns'
  }
];
